### ISSUE TITLE
Mysql 21.0.2 incompatible with poem-openapi 1.0.31

### ISSUE THREAD

**Issue by Christoph-AK** [poem-web/poem#100]
Hey there,
I would like to use Poem with Mysql, but they seem to be using incompatible bitvec / funty versions. On build I get a `
error[E0034]: multiple applicable items in scope
   --> C:\Users\local\.cargo\registry\src\github.com-1ecc6299db9ec823\bitvec-0.19.4\src\field.rs:307:25`. 

This problem seems to be known in funty and can apparently be solved by updating all dependencies to funty 2.0.0 (or at least the same version.) Unfortunately it is nested quite deeply in the dependencies. 

Example Toml, full build output, and cargo tree output uploaded here: https://gist.github.com/Christoph-AK/366e6c39c24976d5bf48064e658b6670

Can this be solved from this crate?

MySQL Issue: https://github.com/blackbeam/rust-mysql-simple/issues/300

**Comment by sunli829** [comment]
Have you enabled the `staticfiles` or `template` feature?

**Comment by Christoph-AK** [comment]
Not explicitly, as per the cargo.toml in the gist. 
Are they included in default?
Is either likely to impact this problem?

**Comment by sunli829** [comment]
Please upgrade to `v1.0.33`, it removes `akasma` from dependencies.

**Comment by Christoph-AK** [comment]
Wow, thanks for looking into it so quickly! My projects now build successfully, thank you! And sorry for the inconvenience and having to rip the templating out. This is such an annoying problem which normally shouldn't happen in the first place, but afaik funty screwed up their semantic versioning or something like that...
