### ISSUE TITLE
PgSessionStore

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#103]
Hi @sunli829, awesome work as always! this library looks as clean as `async-graphql` and +1 for the name 😄 

## Description of the feature

Currently it does not support `PgSessionStore`, so you have any thought about it?

Like should it be here or which library to use with Pg?

**Comment by sunli829** [comment]
In fact this is very easy, you only need to implement [` SessionStore `] (https://docs.rs/poem/1.0.34/poem/session/trait.SessionStorage.html), if you don't know how to do, I can give you an example tomorrow.😄

**Comment by shujaatak** [comment]
> In fact this is very easy, you only need to implement [`SessionStore`](https://docs.rs/poem/1.0.34/poem/session/trait.SessionStorage.html), if you don't know how to do, I can give you an example tomorrow.smile

Example please :smile:

**Comment by phungleson** [comment]
Yeah thanks Sunil, yeah it would be very helpful to have some clues

Or even more beneficial for a lot of people if it becomes a small crate we can use like these ones.

https://github.com/http-rs/async-session
https://github.com/jbr/async-sqlx-session

**Comment by sunli829** [comment]
I added `poem-dbsession` crate.

https://github.com/poem-web/poem/tree/master/poem-dbsession

**Comment by phungleson** [comment]
Awesome! thanks @sunli829

I will keep this alive for a while so people are aware of new crate.
