### ISSUE TITLE
Nested routing with middleware

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#104]
Hi @sunli829 

This is probably due to my limited knowledge of poem, but basically I would like to use `async_graphql` with poem with `SizeLimit` middleware.

```
GET app/query => playground
POST app/query => async_graphql with size limit
```

My code is something like this at the moment

```rust
fn app() -> Route {
    let schema = ...;

    Route::new().at(
        "query",
        get(graphql_playground)
        .post(GraphQL::new(schema))
         // .with(SizeLimit::new(CONTENT_LENGTH_LIMIT)),
    )
}

let app = Route::new().nest("app", app());
```

If I uncomment `SizeLimit` then I get 400 for `GET app/query` as the middleware blocked it.

Can you suggest a way to make this work?

**Comment by sunli829** [comment]
> If the incoming request does not contain the `Content-Length` header, it will return `BAD_REQUEST` status code.

GET request does not contains the `Content-Length` header, so `SizeLimit` should only be used for `POST` requests.

```rust
Route::new().at(
        "query",
        get(graphql_playground)
        .post(GraphQL::new(schema).with(SizeLimit::new(CONTENT_LENGTH_LIMIT)))
    )
```

**Comment by phungleson** [comment]
Awesome! mind-blown by how flexible and neat poem middleware is 🤯 😄
