### ISSUE TITLE
PgSessionStore to be used with nested routing

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#106]
Hi @sunli829 

Again, this is probably due to my limited knowledge of poem.

Basically, I want to use `PgSessionStore`.

```rust
Route::new().at(
    "query",
    post(GraphQL::new(schema))
    .get(graphql_playground)
    .with(server_session),
)
```

It throws error ```the trait bound `impl std::future::Future: SessionStorage` is not satisfied```

If I try something like the example

```rust
Route::new().at(
    "query",
    post(GraphQL::new(schema))
    .get(graphql_playground),
).with(server_session)
```

Then I don't know how to turn in back as a `Route` (am setting up nested routing).

**Comment by sunli829** [comment]
`PgSessionStorage::new` is an asynchronous method.

**Comment by phungleson** [comment]
Thanks @sunli829 it works!
