### ISSUE TITLE
Debug for Extensions

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#107]
I am developing some middleware and it seems a bit hard to know how `req.extensions` looks like.

It would be helpful if I can debug `Extensions` so that I can tell how the middleware interacts with each other.

Thanks.

**Comment by phungleson** [comment]
Actually I figure out how my middleware work, feel free to close if you think it is not necessary.

**Comment by sunli829** [comment]
Middleware is very simple, it is used to wrap one endpoint for another.

**Comment by sunli829** [comment]
Middleware is very simple, it is used to wrap one endpoint for another.

**Comment by phungleson** [comment]
Yeah I got more familiar with it and it seems relatively easy and flexible!
