### ISSUE TITLE
Couple of observation regarding dbsession

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#109]
Good day @sunli829 

I am still testing with `poem`, I want to share small observation with `dbsession` for consideration or further checking.

1. For postgres, not sure if it is correct or not but it looks like it will fail if session column is not JSONB. If it is then maybe there should be a note.

2. Cleanup task should probably be configurable. When we have multiple poem servers running, we probably don't want every server to ping database to do clean up. I am not sure what the best way to approach this as some pros and cons of each setup or we just need to accept the duplicate jobs?

3. Not very high priority, the value of in session in db looks like this `{"id": "\"xxx\""}`, it looks like the library does serialising twice at some points. It doesn't seem to affect how it works, nevertheless it is kind of nice to have correct json presentation.

**Comment by sunli829** [comment]
> For postgres, not sure if it is correct or not but it looks like it will fail if session column is not JSONB. If it is then maybe there should be a note.

Yes, if you use postgres, the session column must be `jsonb`.

https://github.com/poem-web/poem/blob/84e27e6b83cfd1f5c644dde9691284c8bd513770/poem-dbsession/src/sqlx/postgres.rs#L31

> Cleanup task should probably be configurable. When we have multiple poem servers running, we probably don't want every server to ping database to do clean up. I am not sure what the best way to approach this as some pros and cons of each setup or we just need to accept the duplicate jobs?

You are right, so I changed it, and now only provides a `cleanup` function, users need to call it themselves.

> Not very high priority, the value of in session in db looks like this {"id": "\"xxx\""}, it looks like the library does serialising twice at some points. It doesn't seem to affect how it works, nevertheless it is kind of nice to have correct json presentation.

It does serialize twice, but works fine. 🙂

**Comment by phungleson** [comment]
> Not very high priority, the value of in session in db looks like this {"id": ""xxx""}, it looks like the library does serialising twice at some points. It doesn't seem to affect how it works, nevertheless it is kind of nice to have correct json presentation.


> It does serialize twice, but works fine. 🙂

Yeah looks like it is due to Session is using `entries: BTreeMap<String, String>`, coming from other languages I see people keep session in a more flexible JSON format.

https://github.com/gorilla/sessions/blob/master/sessions.go#L36

Not saying it is the standard but just something from prior art to consider.

**Comment by sunli829** [comment]
I thought you didn't care about this. 🙂

**Comment by sunli829** [comment]
Fixed in `v.1.2.8`

**Comment by phungleson** [comment]
Awesome thx!

I was taking a break so that you can do more productive work elsewhere  jk jk ;)

Btw some shower thoughts this morning, happy if you say the following idea is not worth the effort.. etc..:

Basically in Go, people extract session into a separate library https://github.com/gorilla/sessions so that it can grow by itself, i.e. used for different servers or different stores. Not sure if it is worth doing the same thing in Rust? since poem session looks more or less self contained already. 

I am not sure how other servers would use it though, cheers

**Comment by phungleson** [comment]
I am closing this as nothing much to do about it and it is end of the year.

Happy NY to you, have a good time with family and friends! @sunli829
