### ISSUE TITLE
Clone for RequestBuilder

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#110]
I am not sure it is a common use case but I am making lots of requests (mainly for testing) and each of them is slightly different.

So I am thinking of using `RequestBuilder` so that I can share some common headers.. etc...

However whenever I consume it into `Request` I cannot use `request_builder` any more, it would be helpful if `RequestBuilder` is cloneable.

Thanks!

**Comment by sunli829** [comment]
This cannot be achieved because `Extensions` cannot be cloned. 🙂

**Comment by phungleson** [comment]
Yeah thanks, okay I will DIY for now.
