### ISSUE TITLE
Incorrect path to handler in openapi specification

### ISSUE THREAD

**Issue by szagi3891** [poem-web/poem#111]
## Expected Behavior
Api1 has been installed in routing under /api1.
I would expect such a specification to be generated :

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Oneof",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/api1"
    }
  ],
  "tags": [],
  "paths": {
    "/api1/create-post": {
      "post": {
```

## Actual Behavior

Extract from the current specification http://127.0.0.1:3000/spec1.json

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Oneof",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/api1"
    }
  ],
  "tags": [],
  "paths": {
    "/create-post": {
      "post": {
```

## Steps to Reproduce the Problem

I created a test repository https://github.com/szagi3891/poem-test
You have to clone and then run with cargo run
A swagger will be available at "http://127.0.0.1:3000/ui1"

## Specifications

Version: poem = "1.0.34", poem-openapi = "1.0.35"
Platform: MacOs
Subsystem:

```
struct Api1 {}

#[OpenApi]
impl Api1 {
    pub fn new() -> Api1 {
        Api1 {}
    }

    #[oai(path = "/create-post", method = "post")]
    async fn create_post(
        &self,
        obj: Json<MyObj>,
    ) -> CreateBlogResponse {

        CreateBlogResponse::Ok(Json(444))
    }
}
```

```

    let api1 = Api1::new();

    let api_service1 = OpenApiService::new(api1, "Oneof", "1.0").server("http://localhost:3000/api1");
    let ui1 = api_service1.swagger_ui();
    let spec1 = api_service1.spec_endpoint();


    let api2 = Api2::new();

    let api_service2 = OpenApiService::new(api2, "Oneof", "1.0").server("http://localhost:3000/api2");
    let ui2 = api_service2.swagger_ui();
    let spec2 = api_service2.spec_endpoint();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(Route::new()
            .nest("/spec1.json", spec1)
            .nest("/api1", api_service1)
            .nest("/ui1", ui1)
            .nest("/spec2.json", spec2)
            .nest("/api2", api_service2)
            .nest("/ui2", ui2)
        )
        .await
        
```

**Comment by szagi3891** [comment]
This method could potentially take an additional parameter:
let spec1 = api_service1.spec_endpoint("/api1");

which would specify the base address to which this part of the api has been mounted.

It would probably be a good idea to add such a parameter also for the method :
let ui1 = api_service1.swagger_ui();

**Comment by sunli829** [comment]
```
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
```

When I changed the method to `POST`, everything worked fine.


```rust
#[oai(path = "/hello", method = "post")]
async fn create_post()
```

**Comment by szagi3891** [comment]
The point is that the "create_post" method is available at: "http://127.0.0.1:3000/api1/hello"

If I send this http request:
```
POST http://127.0.0.1:3000/api1/hello
Content-Type: application/json
Accept: application/json

{
    "type": "A",
    "v1": 0,
    "v2": "dddsssaaaa"
}
```

I will receive a reply from the server:
```
HTTP/1.1 200 OK
content-type: application/json
content-length: 3
date: Sun, 05 Dec 2021 13:17:57 GMT

444
```

This behaviour is obviously correct.

The problem is that the path in the specification is generated like this:
```
"paths": {
  "/hello": {
    "post": {
```
In the specification, the location should be "/api1/hello".

**Comment by szagi3891** [comment]
I made a new handler in this sample repo: http://127.0.0.1:3000/spec1-correct.json

I made a function that changes the generated specification and adds this prefix:
```
fn add_base(base: impl Into<String>, spec: &String) -> String {
```

Question, can this be integrated into poem-openapi somehow ?

**Comment by sunli829** [comment]
> I made a new handler in this sample repo: http://127.0.0.1:3000/spec1-correct.json
> 
> I made a function that changes the generated specification and adds this prefix:
> 
> ```
> fn add_base(base: impl Into<String>, spec: &String) -> String {
> ```
> 
> Question, can this be integrated into poem-openapi somehow ?

Ah, I see what you want, it's easy.

```rust
#[OpenApi(prefix_path = "/api1")]
```

```rust
.nest_no_strip("/api1", api_service1)
```

You only need to change these two places.

**Comment by szagi3891** [comment]
@sunli829 Thank you very much. It works fantastically :)
