### ISSUE TITLE
Log, trace, monitor, error monitoring

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#112]
Hi Sunli, poem seems pretty good so far, I wonder where should I start looking into for in terms of log, trace, monitor, error monitoring before I want to move poem into some sort of production? Thanks!

**Comment by sunli829** [comment]
Maybe this example can help you:

https://github.com/poem-web/poem/tree/master/examples/poem/opentelemetry-jaeger

**Comment by sunli829** [comment]
`PrometheusExporter` can also be used with `OpenTelemetryMetrics`.

```rust
let app = Route::new()
    .at("/exporter", PrometheusExporter::new())
    .with(OpenTelemetryMetrics::new())
```

**Comment by phungleson** [comment]
Thanks! I will take a look.

I will close this for now since it looks like I need some time to setup something first.
