### ISSUE TITLE
Poem_Openapi: Parse Parameter Description per ///

### ISSUE THREAD

**Issue by Christoph-AK** [poem-web/poem#114]
Hey there :) 

Would it be possible to parse Parameter Descriptions via ///-comments, like with struct fields etc, instead of the 'desc=' notation?

I struggled to find descriptions in the first place...

https://github.com/poem-web/poem/blob/7586983c129ccd216d8dd46134a71e0139cdf860/poem-openapi/tests/operation_param.rs#L249

So maybe in this case: 
```
async fn test(&self, 
    /// desc
    v: Query<i32>
) { 
```
or comparable? Or would that be to inconsistent with linebreaks?

**Comment by sunli829** [comment]
Released in `v1.0.37` 🙂

**Comment by Christoph-AK** [comment]
Wow, you are so fast 👍 
I hope this doesn't break too much code of other people 😆
