### ISSUE TITLE
Capture all errors

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#117]
Hi Sunli,

When I test `dbsession`, it throws some explicit errors about the database which is un-intended.

How can we capture all errors, from all endpoints and from all middleware? so that I can mask it with something more friendly to users.

Thanks!

**Comment by sunli829** [comment]
Like this, you can catch any errors.

https://github.com/poem-web/poem/blob/5d21f8a50f6158605b6af9bed47ef1c1dea29d4c/examples/poem/handling-404/src/main.rs#L21

**Comment by phungleson** [comment]
Thanks it works!
