### ISSUE TITLE
Thoughts on SizeLimit

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#120]
I am playing around with `SizeLimit`, it seems that it has something like this `type Output = Result<E::Output>;`

It shows how great and flexible poem is, however it also make the API less uniformed.

For example, when I try to capture all errors I have to take `Result<Response>` as param instead of `Response`, also status code can come either from `reponse.status_code()` or `error.status_code()`. I wonder if it is worth making the `Output` uniform as `Response`?

I am not sure what the cons though, maybe other middleware really need the `Output` to be flexible?

**Comment by sunli829** [comment]
I recommend always using the status code to determine the type of error.

You can always use `EndpointExt::map_to_response` to convert the output of an endpoint to `Response`.

```rust
Route::new().at(...).at(...).with(...).map_to_response().after(|resp| ...)
```

**Comment by phungleson** [comment]
Oh nice, yeah I was looking for something like `map_to_response()` cheers!
