### ISSUE TITLE
Benchmark vs other popular library

### ISSUE THREAD

**Issue by totaland** [poem-web/poem#124]
Hi,
Love what you are trying to do. (Awesome other libraries like async graphql for example)

I was wondering if you have a benchmark and features comparisons with other web frameworks.

A couple of examples I found:

https://web-frameworks-benchmark.netlify.app/result?asc=0&metric=totalRequestsPerS&order_by=level64

https://react-query.tanstack.com/

Also, is this still a work in progress and not ready for production?

**Comment by sunli829** [comment]
> I was wondering if you have a benchmark and features comparisons with other web frameworks.

I will add this when I am free.

> Also, is this still a work in progress and not ready for production?

Poem has been stable, and there are many projects based on it, but there is no open source.

**Comment by nashley** [comment]
There are multiple problems with the benchmarking setup (e.g., using the same computer for the client and server), and the example is so contrived as to be practically useless, but here's what I got from a simple, static `Hello, World!` implementation written with `poem`:
```
Benchmarking 500 connections @ http://127.0.0.1:3000 for 30 second(s)
  Latencies:
    Avg      Stdev    Min      Max
    2.18ms   1.36ms   0.03ms   210.88ms
  Requests:
    Total: 6820539 Req/Sec: 228461.07
  Transfer:
    Total: 748.03 MB Transfer Rate: 25.06 MB/Sec
```
For reference, here's what a plain-`hyper` benchmark got:
```
Benchmarking 500 connections @ http://127.0.0.1:3000 for 30 second(s)
  Latencies:
    Avg      Stdev    Min      Max
    2.10ms   1.37ms   0.03ms   235.84ms
  Requests:
    Total: 7084513 Req/Sec: 237460.70
  Transfer:
    Total: 601.31 MB Transfer Rate: 20.15 MB/Sec
```
And here's `actix-web`:
```
Benchmarking 500 connections @ http://127.0.0.1:3000 for 30 second(s)
  Latencies:
    Avg      Stdev    Min      Max
    1.86ms   1.40ms   0.03ms   80.78ms
  Requests:
    Total: 8002091 Req/Sec: 268218.15
  Transfer:
    Total: 992.08 MB Transfer Rate: 33.25 MB/Sec
```
You can find and run these (again, uselessly simplistic) tests for yourself [here](https://github.com/programatik29/rust-web-benchmarks/pull/5) if you want.
Hopefully that gives you a rough idea of where `poem` stands amongst other http frameworks when handling totally unrealistic, synthetic traffic.

**Comment by programatik29** [comment]
> totally unrealistic, synthetic traffic.

This favors `actix-web` setup since it doesn't have work stealing.
