### ISSUE TITLE
Vague error from ServerSession

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#125]
Hi Sunli,

I am still playing `ServerSession`, and I think it throws some error here

https://github.com/poem-web/poem/blob/master/poem/src/session/server_session.rs#L66

But after that middleware it looks like I only have `poem::Response`, how can I access to the source of the error to know what might go wrong?

Cheers,

**Comment by sunli829** [comment]
`poem::Response` contains the reason string for this error, and the status code is `503`.

**Comment by phungleson** [comment]
Thanks it works!

BTW, why can't we borrow the body, I have to do something like `response.into_parts()`. Just curious not sure where the pattern `into_parts` comes from?

**Comment by sunli829** [comment]
Can you tell me why you want to borrow the body?

**Comment by phungleson** [comment]
Ah I was trying to log out the body to debug.

**Comment by sunli829** [comment]
I understand, you want to log he error, but if you read the content of the body it will consume it, let me think about it.

**Comment by sunli829** [comment]
Please upgrade to `v1.2.1`.

Now `Endpoint` always returns `Result<T, Error>`, `Error` provides `is` and `downcast_ref` to get the concrete error type.

```rust
let app = Route::new().inspect_err(|err| {
    if err.is::<sql::Error>() {
       // do something
    }
});
```

**Comment by phungleson** [comment]
Thanks @sunli829 sorry I am a little bit busy to test this out. I will take a look when I have a chance.

I am sure it will work perfectly well 😄
