### ISSUE TITLE
Inter middleware dependency

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#127]
## Description of the feature

Not sure if it is meant to work this way but it looks like if I want `middleware1` to be called before `middleware2` (inter middleware dependency) using `.with` I have to chain them like this `.with(middleware2).with(middleware1)`, i.e. `middleware2` before `middleware1`, instead of natural `middleware1` before `middleware2`

Something like this:

```
Route::new()
        .at(...)
        .with(middleware2)
        .with(middleware1)
```

If it is meant to be this way, maybe we should have some note in the book somehow.

Or nicer if we can make it work like this, i.e. `middleware1` before `middleware2`, it looks more more natural.

```
.at(...).with(middleware1).with(middleware2)
```

**Comment by sunli829** [comment]
Based on the principle of `poem` middleware, this is impossible to achieve. 😂

**Comment by phungleson** [comment]
Yeah thanks Sunil, I wonder if something similar like this is easier

```
.at(...).with(middleware1.with(middleware2))
```

So that relationship between `middleware1` and `middleware2` is somewhat clearer. It probably looks a bit un-necessarily nested though.

**Comment by sunli829** [comment]
If you understand the working principle of middleware, the current solution is easier to understand. 🙂

**Comment by phungleson** [comment]
Yeah current structure seems nice and concise.

Maybe just a note about the sequence of execution of the middlewares is good enough for anyone who might be wondering.

**Comment by phungleson** [comment]
Alright I am closing this as it isn't anything significant.

I am happy with poem middleware 🙂
