### ISSUE TITLE
Multiple similar interfaces may cause unexpected parse result

### ISSUE THREAD

**Issue by xgjhlws** [poem-web/poem#129]
## Expected Behavior
It Parse interface correctly when running or warn developer when compiling.
If possible, i want it parse interface correctly.

## Actual Behavior
unexpected parse result

## Steps to Reproduce the Problem
I have two interfaces which like this :

``` rust
let app = Route::new().at(
    "/api/:organization/:asset/cover",
    get(get_cover).post(post_cover).patch(patch_cover),
)
.at(
    "/api/:organization/prefabcombination/:id",
    get(api::prefabcombination::get_combination),
)
.with(......);
```
When I call:
``` 
method=GET path=/api/muse/prefabcombination/cover
```
Result:
It parsed the interface and called function "get_combination". But in actix-web we used before it can parse correctly and call function "get_cover". What we want is "get_cover" here.

## Specifications

- Version: 
 rustc 1.59.0-nightly (e6b883c74 2021-12-08)
 cargo 1.58.0-nightly (40dc28175 2021-12-06)
 poem = {version = "1.1", features=["websocket", "session", "multipart", "rustls", "compression"] }
- Platform: windows 10 
- Subsystem:

**Comment by sunli829** [comment]
`actix-web` uses regular expressions to match routes in the order of adding paths, and `poem` uses the radix tree, which is why this can be matched correctly in `actix-web`.

The two path patterns themselves are in conflict, `/api/muse/prefabcombination/cover` can match any one, so this is not a bug.

**Comment by xgjhlws** [comment]
@sunli829 If it is not considered to be a bug, can poem make a warning in this case?

**Comment by sunli829** [comment]
In fact, I think the current behavior is fully in line with expectations, and there is no need to add this warning.  😁

**Comment by sunli829** [comment]
In fact, I think the current behavior is exactly as expected, and there is no need to add a warning for this. 😁
