### ISSUE TITLE
<Title>poem-openapi-1.2.9 registry\mod.rs:628:25  have the same OpenAPI name ？

### ISSUE THREAD

**Issue by lqfluohang** [poem-web/poem#132]
thread 'main' panicked at '`lz_account_service::models::PageResp<lz_account_service::models::account_log_model::AccountLogModel>` and `lz_account_service::models::PageResp<lz_account_service::models::account_transfer_model::AccountTransferModel>` have the same OpenAPI name `PageResp`', C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\poem-openapi-1.2.9\src\registry\mod.rs:628:25

#[derive(Clone, Debug, PartialEq, Object)]
pub struct PageResp<T> 
where T:Clone  + PartialEq + ToJSON + ParseFromJSON,
{
    pub page:u32,
    pub total:u32,
    pub page_size:u32,
    pub data_list:Vec<T>
}

#[oai(
        path = "/account/:account_id/account-log/",
        method = "get",
        tag = "ApiTags::Account"
    )]
    async fn index_account_log(
        &self,
        db: Data<&DbConn>,
        account_id: Path<i64>,
        page: Query<Option<u32>>,
    ) -> Result<Json<PageResp<AccountLogModel>>> {
        let v_account_id = account_id.0;
        let page = page.0.unwrap_or(1);
        let page = if page > 0 { page } else { 1 };
        let page_size = 10;
        info!("查找账号信息id:{}", v_account_id);
        if v_account_id < 1 {
            return Err(Error::from_string("没有找到数据", StatusCode::NOT_FOUND));
        }
        let db = db.0;
        let result = AccountService::index_account_log(v_account_id, page, page_size, db).await;
        match result {
            Ok(v_paginate) => Ok(Json(v_paginate)),
            Err(e) => Err(Error::new(e, StatusCode::SERVICE_UNAVAILABLE)),
        }
    }

#[oai(
        path = "/account-transfer/user/:user_id/",
        method = "get",
        tag = "ApiTags::AccountTransfer"
    )]
    async fn index_user_transfer(
        &self,
        db: Data<&DbConn>,
        user_id: Path<i64>,
        page: Query<Option<u32>>,
    ) -> Result<Json<PageResp<AccountTransferModel>>> {
        let v_user_id = user_id.0;
        let page = page.0.unwrap_or(1);
        let page = if page > 0 { page } else { 1 };
        let page_size = 10;
        info!("查找账号信息id:{}", v_user_id);
        if v_user_id < 1 {
            return Err(Error::from_string("没有找到数据", StatusCode::NOT_FOUND));
        }
        let db = db.0;
        let result =
            AccountTransferService::index_user_transfer(v_user_id, page, page_size, db).await;
        match result {
            Ok(v_paginate) => Ok(Json(v_paginate)),
            Err(e) => Err(Error::new(e, StatusCode::SERVICE_UNAVAILABLE)),
        }
    }

**Comment by sunli829** [comment]
Your `PageResp` object is a generic object, so need to give the name of each concrate type.

https://github.com/poem-web/poem/blob/fad3f30498f0082abb5e92e8b15375ee40e46c9b/poem-openapi/tests/object.rs#L39

**Comment by lqfluohang** [comment]
#[oai(
        concrete(name = "Obj_i32_i64", params(i32, i64)),
        concrete(name = "Obj_f32_f64", params(f32, f64))
    )]

thanks

大哥 能不能 方便代码的编写，不要写这么麻烦？
我没有花很多时间看代码， 所以不知道为什么要加上这样的限制？是不是为了生成swagger 文档？

**Comment by sunli829** [comment]
OpenAPI does not support generics, so each concrete type must be named.

Inline object does not need a name, you can use the `inline` attribute, like this:

```
#[derive(Clone, Debug, PartialEq, Object)]
#[oai(inline)]
pub struct PageResp<T>
where T:Clone + PartialEq + ToJSON + ParseFromJSON,
{
pub page:u32,
pub total:u32,
pub page_size:u32,
pub data_list:Vec
}
```

**Comment by lqfluohang** [comment]
Thanks
已经成功升级到1.2.29
