### ISSUE TITLE
<Title> How can Middleware get Data<&DbPool> ? 如何在 Middleware 获取Data<&DbPool> ？

### ISSUE THREAD

**Issue by lqfluohang** [poem-web/poem#134]
use poem::{
    async_trait, get, handler, listener::TcpListener, Endpoint, EndpointExt, IntoResponse,
    Middleware, Request, Response, Result, Route, Server,
};

struct Log;

impl<E: Endpoint> Middleware<E> for Log {
    type Output = LogImpl<E>;

    fn transform(&self, ep: E) -> Self::Output {
        LogImpl(ep)
    }
}

struct LogImpl<E>(E);

#[async_trait]
impl<E: Endpoint> Endpoint for LogImpl<E> {
    type Output = Response;

    async fn call(&self, req: Request) -> Result<Self::Output> {

      ###  let db = req.extensions().get::<DbPool>()

        println!("request: {}", req.uri().path());
        let res = self.0.call(req).await;

        match res {
            Ok(resp) => {
                let resp = resp.into_response();
                println!("response: {}", resp.status());
                Ok(resp)
            }
            Err(err) => {
                println!("error: {}", err);
                Err(err)
            }
        }
    }
}

**Comment by sunli829** [comment]
```rust
req.extensions().get::<DbPool>()
``
