### ISSUE TITLE
<Title>poem_openapi::Object  struct  chrono::DateTime   the trait `ToJSON` is not implemented

### ISSUE THREAD

**Issue by lqfluohang** [poem-web/poem#135]
这里需要怎样配置？
使用#[oai ] 不知道怎样配置？我看到源代码有 poem-openapi\src\types\external\datetime.rs 有这个类型
但是不知道怎样写？

the trait `ToJSON` is not implemented for `chrono::DateTime<Utc>`？
 
#[derive(Clone, Debug, PartialEq, Object)]
#[oai(rename_all = "camelCase")]
pub struct AuthSysUserModel {
    pub id: i64,
    pub name: Option<String>,
    pub status: Option<i32>,
    pub date_created: Option<DateTime<Utc>>,
    pub last_updated: Option<DateTime<Utc>>,
}

**Comment by sunli829** [comment]
Add the `chrono` feature to `Cargo.toml`

**Comment by lqfluohang** [comment]
poem-openapi = { version = "1.2.9", features = ["swagger-ui", "chrono"] }
