### ISSUE TITLE
Customize Bearer authentication extraction with OpenAPI

### ISSUE THREAD

**Issue by Mcfloy** [poem-web/poem#136]
Hello and thanks for making this cool framework, I'm trying to work on this case with the openapi feature so that the API is more user-friendly.

So I took example on the [basic auth](https://github.com/poem-web/poem/blob/master/examples/openapi/auth-basic/src/main.rs) but with a Bearer authentication, works perfectly! But there's a downside, it's that I'm using JWT and that I want to accept only the JWT that my server signed.

I managed to simulate the concept with a custom struct named `Principal` that implements the `FromRequest` trait, and on the routes I want to protect I just have to ask for a `_principal: Principal` argument (in this case I don't use it)

Now the problem is that I can't actually protect the routes on the SwaggerUI page with this because `Principal` can't have a derive SecurityScheme.

The usage of JWT with a Bearer header is actually common where I'm working and the implementation is actually very simple (I'm using the `jsonwebtoken` to decode the token into the `Principal` struct)

What I would need is some help about having the similar behavior of the bearer implementation from the framework with the custom handling I've made.

Or another hypothesis that could also do the job is put a middleware onto the Bearer Authentication so that I can inspect the extracted token from poem and check if it's a valid JWT, without having to call the method at each beginning of the routes.

**Comment by sunli829** [comment]
This is easy, just do the following.

```rust
#[derive(SecurityScheme)]
#[oai(type = "bearer")]
struct MySecurityScheme(Bearer);
```

If you want to add validation, do it like the following.

```rust
struct Principal {
    username: String,
}

#[derive(SecurityScheme)]
#[oai(type = "bearer", checker = "token_checker")]
struct MySecurityScheme(Principal);

async fn token_checker(_: &Request, bearer: Bearer) -> Option<Principal> {
    // Returns `Some` if the parsing of jwt is successful
}

struct MyApi;

#[OpenApi]
impl MyApi {
    #[oai(path = "...", method = "get")]
    async fn get_something(&self, token: MySecurityScheme) {
    }
}
```

**Comment by Mcfloy** [comment]
Using your example I would like to do something like this:
```rust
#[OpenApi]
impl MyApi {
    #[oai(path = "...", method = "get")]
    async fn get_something(&self, token: MySecurityScheme) -> PlainText(String) {
      PlainText(auth.0.username)
    }
}
```

However the rust compiler is stating that field `0` is private, but the [api key example](https://github.com/poem-web/poem/blob/master/examples/openapi/auth-apikey/src/main.rs) is similar.

Is it a bug ?

**Comment by sunli829** [comment]
I guess your `MySecurityScheme` is defined in another module, so you should make the members of `MySecurityScheme` public.

```rust
#[derive(SecurityScheme)]
#[oai(type = "bearer", checker = "token_checker")]
struct MySecurityScheme(pub Principal);
```

**Comment by Mcfloy** [comment]
The solution is so obvious I feel dumb not thinking about it earlier, thanks a lot of the help it does work perfectly :+1:
