### ISSUE TITLE
Is there a jwt token example?

### ISSUE THREAD

**Issue by limodou** [poem-web/poem#138]
There is no jwt token example. And I want to know how to save token or parsed user info into request, and how to get back in handler function.

**Comment by sunli829** [comment]
You can do it like this:

https://github.com/poem-web/poem/blob/ff56f9f5eb83c797516745f3e729c5b506da25c4/poem/src/middleware/mod.rs#L49

**Comment by limodou** [comment]
How should I store the parsed token into a request, and get back when I need. The stored token should associate with each request. Should I use session?

**Comment by sunli829** [comment]
Parse and attach the token to each request.

https://github.com/poem-web/poem/blob/ff56f9f5eb83c797516745f3e729c5b506da25c4/poem/src/middleware/mod.rs#L87

Extract the token from incoming request:

https://github.com/poem-web/poem/blob/ff56f9f5eb83c797516745f3e729c5b506da25c4/poem/src/middleware/mod.rs#L96

**Comment by sunli829** [comment]
If you still don't understand what to do, I can provide an example.

**Comment by limodou** [comment]
I see. Using request.extension to save the data that will attach it to each request.

**Comment by sunli829** [comment]
Exactly！
