### ISSUE TITLE
How to force https?

### ISSUE THREAD

**Issue by wileymc** [poem-web/poem#139]
What is the best way to force HTTPS for the whole app? In express it would look something like this: 
```
app.use((req, res, next) => {
  if (req.header('x-forwarded-proto') !== 'https') {
    res.redirect(`https://${req.header('host')}${req.url}`)
  } else {
    next();
  }
});
```

**Comment by sunli829** [comment]
This is currently not supported, I will add this now.

**Comment by sunli829** [comment]
I added a `ForceHttps` middleware in the `1.2.13` version.

**Comment by wileybaba** [comment]
You're a legend @sunli829

**Comment by wileybaba** [comment]
Hey @sunli829 could you show an example of how to use this new middleware? I tried this:
```rust
    let app = Route::new()
        .at("/", get(graphql_playground).post(graphql_handler))
        .data(schema)
        .with(Cors::default())
        .with(ForceHttps::default());

    let port = std::env::var("PORT").unwrap_or_else(|_| "1234".to_string());
    let address = format!("0.0.0.0:{}", port);

    info!("GraphQL Playground live at {}/playground", &address);

    let listener = TcpListener::bind(&address);
    let server = Server::new(listener);
    server.run(app).await?;
    Ok(())
```
And that seems to cause `ERR_TOO_MANY_REDIRECTS` in production and `ERR_SSL_PROTOCOL_ERROR` for localhost

**Comment by wileybaba** [comment]
Looks like force HTTPS is now the default for v1.2.15 @sunli829 ?

**Comment by sunli829** [comment]
The `ForceHttps` middleware will redirect `http://host/path` to `https://host/path`, and the web browser will choose a different port according to the scheme.

But if your url is `http://host:3000/path`, then it will be redirected to `https://host:3000/path`, which is incorrect.

To support this, I added `ForceHttps::https_port` method to the `ForceHttps` middleware, you can use it to specify the port.

**Comment by sunli829** [comment]
Released in `v1.2.16`

**Comment by wileybaba** [comment]
Nice! This is working great everywhere except for localhost, where it redirects http://localhost:1234 to https://localhost:1234, even with the `https_port` specified.  I solved this with a simple if-else that uses and ENVIRONMENT env variable:
```rust
if environment == Environment::Local {
        Server::new(listener).run(app).await
    } else {
        Server::new(listener)
            .run(app.with(ForceHttps::default()))
            .await
    }
```

**Comment by wileymc** [comment]
Would it be possible to check for optionally check for HTTPS using the X-Forwarded-Proto header?  Unfortunately this middleware causes ERR_TOO_MANY_REDIRECTS in heroku deployments due to this: https://help.heroku.com/VKLSBMJS/why-am-i-getting-a-message-too-many-redirects
