### ISSUE TITLE
Poem generates a field with `#[oai(default)]` marked as `required` even though it isn't.

### ISSUE THREAD

**Issue by ChillFish8** [poem-web/poem#145]
## Expected Behavior
When marking a field with `#[oai(default)]` you'd expect to see it be marked as not required on the openapi spec like marking a field with `Option<T>`

## Actual Behavior
 Instead of the above, the defaulting behaviour works as expected but the spec labels the field as required.

![image](https://user-images.githubusercontent.com/57491488/147766427-c65f143c-e7ac-4f9f-b822-62ab5b86b2e5.png)

We see the fields marked as required despite defaulting correctly when sending a POST request with the following payload:
```json
{
  "title": "string"
}
```

**Console output**
```
[src\rooms\mod.rs:82] &payload.0 = RoomCreationPayload {
    title: "string",
    topic: None,
    active_playlist: None,
    guild_id: None,
    banner: None,
    invite_only: false,
    is_public: false,
}
```

## Steps to Reproduce the Problem

1. Setup a standard project and have an example API that requires a given POST JSON body like such:
```rust
#[derive(Object, Debug)]
pub struct ExamplePayload {
    #[oai(default)]
    foo: bool,

    #[oai(default)]
    bar: bool,
}
```
2. Observed the generated OpenAPI spec / redoc page shows the field as required but will allow for an empty payload.

## Specifications

- Version: `poem 1.12.17`
- Platform: Windows 10 Pro

**Comment by sunli829** [comment]
I need to look at the JSONSchema specification, @dbanty do you have any suggestions?

**Comment by sunli829** [comment]
Fixed in `v1.2.18`

**Comment by ChillFish8** [comment]
Just tested it and worked perfectly!

**Comment by dbanty** [comment]
> I need to look at the JSONSchema specification, @dbanty do you have any suggestions?

Looks like the right call to me! IIRC there is nothing preventing both from being set (required + default) but it's totally unclear how that should resolve. So just removing the conflict sounds great!
