### ISSUE TITLE
ToJSON vs Serialize

### ISSUE THREAD

**Issue by dbanty** [poem-web/poem#147]
I'd like to have some responses that contain a static string (`&'static str`) which are not `DeserializeOwned` so cannot be `#[Object]`. However, I don't need to be able to deserialize these, only serialize them as they are only responses. This lead me to think it'd be nice to be able to do something like this:

```rust
#[derive(ApiResponse)]
enum Response {
    #[oai(status = 400)]
    BadRequest(Json<ErrorPayload>),
}

#[derive(Serialize)]
struct ErrorPayload {
    code: &'static str,
    message: String,
}
```

Where `Json<T>` would accept any T which is `Serialize`. I tried a quick blanket implementation of `impl <T: Serialize + Type> ToJSON for T` but is some refactoring work to be done in order to make that work.

Before I go down that road, I have a few questions:
1. What's the motivation for `ToJSON` vs just using `Serialize` + `serde_json` everywhere? I don't want to wander down this path and step in the same holes you probably already have 😅.
2. Has that blanket impl already been attempted somewhere, and if so are there any roadblocks I'd hit if I try?

Similarly, I'm going to struggle a bit with needing `Type` as well. I'm considering a `#[derive(Type)]` which I could maybe steal from the `#[Object]` macro, though realistically I think it just needs to inspect the type and pick the right basic impl (e.g., "object" for a `struct`). This could also maybe utilize `serde` but I figure that would be slow at runtime.

---

This isn't urgent, I'm just going to use `String` for now, but I'd like to avoid excess allocations at some point when I don't need them.

**Comment by sunli829** [comment]
`serde` is a general serialization framework, but it does not cover all the features defined in the `JSONSchema` specification.

If the `ErrorPayload` object is only used for output, you can use `read_only` attribute.

```
#[derive(ApiResponse)]
enum Response {
    #[oai(status = 400)]
    BadRequest(Json<ErrorPayload>),
}

#[derive(Object)]
struct ErrorPayload {
    #[oai(read_only)]
    code: &'static str,
    message: String,
}
```

Or use the `read_only_all` attribute.

```
#[derive(ApiResponse)]
enum Response {
    #[oai(status = 400)]
    BadRequest(Json<ErrorPayload>),
}

#[derive(Object)]
#[oai(read_only_all)]
struct ErrorPayload {
    code: &'static str,
    message: String,
}
```

**Comment by dbanty** [comment]
Oh cool, I'll give that a try and maybe think of a place to put that in the docs that I would have discovered it. Maybe just a note in the `#[derive(Object)]`.
