### ISSUE TITLE
Indicate what is wrong with a request for `bad_request_handler`

### ISSUE THREAD

**Issue by dbanty** [poem-web/poem#149]
## Description of the feature

I have a need to return very particular, structured error messages when certain types of bad requests occur. Specifically, if the user forgets to include a required property, I need to indicate that to the user with a structured response which, ideally, includes the name of the property that's missing. If the property was present but failed another validation somehow (e.g., provided the wrong type), I need to return a different error message.

I would like to be able to include this logic in my `bad_request_handler` for my `ApiResponse`, but I don't think I can get enough info out of the `poem::Error` which that takes to get what I need.

## Code example (if possible)

I'd like to be able to do something like this:

```rust
fn bad_request_handler(err: Error) -> Response {
    match err {
        Error::ParseParam{reason, name} => {
            match reason {
                Reason::Missing => make_my_missing_param_error(name),
                Reason::Validation(problem) => make_my_validation_error(name, problem)
            }
        }
       // More cases here
    }
}
```

Where the error that we handle is an enum of all the possible errors which, themselves, may contain more variants. I'm not particular about the implementation though, I just need to be able to return specific error messages based on what part of the request parsing failed 😅.

**Comment by ChillFish8** [comment]
I believe you can do this with a downcast if you use a custom error.

**Comment by sunli829** [comment]
You can do it like this.

```rust
fn bad_request_handler(err: Error) -> Response {
    if err.is::<ParseParamError>() {
        ....
    }
}
```
