### ISSUE TITLE
Poem returns 404 NOT FOUND when accessing a endpoint that exists but doesnt allow that method.

### ISSUE THREAD

**Issue by ChillFish8** [poem-web/poem#150]
## Expected Behavior
Expected to return `405 method not allowed` for endpoints where they exist but only allow a certain set of methods.

## Actual Behavior
Poem will return a 404 if you access an endpoint that exists but with a bad method.

Existing endpoint with correct header:
![image](https://user-images.githubusercontent.com/57491488/147831203-9408466e-8f8d-4898-b373-56efbe2aeaa8.png)

Existing endpoint but with the wrong method:
![image](https://user-images.githubusercontent.com/57491488/147831220-50031a67-73cd-448a-b556-68529a9613f3.png)

**Comment by sunli829** [comment]
Fixed in `v1.2.20` 🙂
