### ISSUE TITLE
Add examples and documentation on the oai macro

### ISSUE THREAD

**Issue by Mcfloy** [poem-web/poem#156]
I struggled a bit by having to look inside the inner code and tests to find out the usages of the oai macro (for example to use the rename_all for serde while having the Object derive)

I've found the usage with the test file however it would be faster to have the usages in the examples folder and the [docs.rs documentation](https://docs.rs/poem-openapi-derive/1.2.25/poem_openapi_derive/derive.Object.html)

The oai is really powerful but lacks documentation for now...

**Comment by dbanty** [comment]
I encountered this same thing, it is all documented, it's just in the `poem-openapi` crate [here](https://docs.rs/poem-openapi/1.2.34/poem_openapi/derive.Object.html)

**Comment by Mcfloy** [comment]
> I encountered this same thing, it is all documented, it's just in the `poem-openapi` crate [here](https://docs.rs/poem-openapi/1.2.34/poem_openapi/derive.Object.html)

Thank you for the link, that's exactly what is needed! I'll close this issue, then.
