### ISSUE TITLE
<Title>combined-apis 功能  元组下元素数量有限制，最多16个API 结构体,  (用中文，英文不好，不好意思)

### ISSUE THREAD

**Issue by lqfluohang** [poem-web/poem#157]
## Expected Behavior
let api_service = OpenApiService::new((Api1, Api2, Api3 ......API100 ), "Combined APIs", "1.0")
        .server("http://localhost:3000/api");

## Actual Behavior
let api_service = OpenApiService::new((Api1, Api2, Api3 ......API16 ), "Combined APIs", "1.0")
        .server("http://localhost:3000/api");

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

- Version:1.12.26
- Platform:
- Subsystem: 

当Handler的数量超过16个就编译不通过，或者用旧的API combine函数来处理也可以，我是从1.2.9 升级本版发现该问题的

代码 错误：

the trait bound `OpenApiService<(SysUserAdminHandler, SysUserHandler, SysUserHandler, CaptchaHandler, SmsHandler, UserHandler, UserAdminHandler, CatalogHandler, CatalogAdminHandler, ProductHandler, ProductAdminHandler, ProductPriceAdminHandler, ProductMediaAdminHandler, ProductDescriptionAdminHandler, PaymentOrderHandler, PaymentOrderAdminHandler, UserOrderHandler, UserOrderAdminHandler), ()>: IntoEndpoint` is not satisfied
   --> src\handler.rs:166:23
    |
166 |         .nest("/api", api_service)
    |          ----         ^^^^^^^^^^^ the trait `IntoEndpoint` is not implemented for `OpenApiService<(SysUserAdminHandler, SysUserHandler, SysUserHandler, CaptchaHandler, SmsHandler, UserHandler, UserAdminHandler, CatalogHandler, CatalogAdminHandler, ProductHandler, ProductAdminHandler, ProductPriceAdminHandler, ProductMediaAdminHandler, ProductDescriptionAdminHandler, PaymentOrderHandler, 
PaymentOrderAdminHandler, UserOrderHandler, UserOrderAdminHandler), ()>`

无法编译

**Comment by sunli829** [comment]
太强了，搞了这么多？

我教你一个骚操作，这些元组可以无限嵌套：

```rust
let api_service = OpenApiService::new((Api1, Api2, Api3), (Api4, Api5, Api6)), "Combined APIs", "1.0")
.server("http://localhost:3000/api");
```

**Comment by lqfluohang** [comment]
谢谢你了，问题解决了
但是，我看源代码，看不出这个问题出现的原因在哪里？
有限制么？

**Comment by umaYnit** [comment]
@lqfluohang 限制在这里。 https://github.com/poem-web/poem/blob/b41eb39e9a/poem-openapi/src/base.rs#L350
