### ISSUE TITLE
Support transparent structs

### ISSUE THREAD

**Issue by bbqsrc** [poem-web/poem#159]
## Description of the feature

Support deriving a primitive type transparently. 

## Code example (if possible)

```rust
#[derive(Object)]
#[oai(transparent)]
struct SomeWrapper(String);
```

I would expect this to then be treated as a "string" in the OpenAPI spec.

**Comment by sunli829** [comment]
Added `NewType` macro in `v1.2.28`.

Here is the test:

https://github.com/poem-web/poem/blob/155a48eca1350a8c49c88b62d2e894ca779fb5a4/poem-openapi/tests/newtype.rs#L4
