### ISSUE TITLE
How to use EventStream?

### ISSUE THREAD

**Issue by JulianZhang** [poem-web/poem#160]
Any one please to give an example or a test case to use the EventStream?

**Comment by sunli829** [comment]
Here is an example: 

https://github.com/poem-web/poem/tree/master/examples/poem/sse

**Comment by JulianZhang** [comment]
@sunli829 你好，这个范例我之前就有看到，因为希望使用框架的swager ui功能，所以使用了poem-openapi。

现在的问题就是不知道如何正确的初始化EventStream，一直报各类trait不满足，能否有一个范例是直接使用EventStream的？

**Comment by sunli829** [comment]
I will provide an example to show how to use SSE with `poem-openapi`.

reference: https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-894718960

**Comment by sunli829** [comment]
https://github.com/poem-web/poem/tree/master/examples/openapi/sse

**Comment by JulianZhang** [comment]
> https://github.com/poem-web/poem/tree/master/examples/openapi/sse

@sunli829  Thanks! I had done my job with the new example.
