### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by Mcfloy** [poem-web/poem#165]
Based on the [json](https://github.com/poem-web/poem/tree/master/examples/poem/json) example.

## Expected Behavior
When the API is being stressed, the memory usage should be relevant compared to the load and then come to a lower level when there isn't any requests. 

## Actual Behavior
When the API is being stressed, the memory usage goes up to handle the incoming requests but doesn't come to a lower level.

## Steps to Reproduce the Problem

1. Use the json example
2. Use a load testing tool like [pewpew](https://github.com/bengadbois/pewpew) with the command `pewpew benchmark http://my-url --rps 1000 -d 30`

## Specifications

- Version: 1.2.28
- Platform: GKE
- Subsystem: distroless/cc

Note: the memory leak seems to be a redundant pattern with other tools like warp and actix web, probably related to tokio or serde_json but I'm not sure. The workaround would be to restart the pod and it will flush the memory, but this is not convenient and goes against Rust's principle of handling the memory usage.

A screenshot of the memory after a heavy load (120k requests after 2 minutes), the initial memory usage was 6MB.
![image](https://user-images.githubusercontent.com/10086193/149534362-db9d35cd-5248-4a66-8b93-251039b6c7b8.png)

**Comment by Mcfloy** [comment]
I'll also leave here a very similar ticket that I've created for actix-web last year that got a lot of discussions about the origin of the "memory leaks": https://github.com/actix/actix-web/issues/1780 where the answer was that there was a cache that would prevent reallocating multiple time a request, and that there's no ttl so it would live until the server is shutdown.

**Comment by sunli829** [comment]
Maybe take a look at this, I just ran some tests and found no obvious memory leaks.

https://github.com/hyperium/hyper/issues/1790

**Comment by Mcfloy** [comment]
After reading it it seems that one of the answers seems relevant:
> I'm assuming this indicates that this memory is actually freed, but the operating system doesn't recognize that?

**Comment by Mcfloy** [comment]
I'll close as this doesn't seems to help that much, but perhaps take into account that restarting the server will clear the memory usage.
