### ISSUE TITLE
Example using templating

### ISSUE THREAD

**Issue by alper** [poem-web/poem#166]
I can't find an example in the examples that uses templating or specifically Tera.

I'm trying to get it to work, but if I try to return:

```
TEMPLATES.render("index", &context)
```

I get:

```
expected struct `poem::Error`, found struct `tera::Error
```

**Comment by alper** [comment]
Got my template to work by returning:

```rust
    TEMPLATES.render("index.html.tera", &context).map_err(|e| {
        println!("Erorr: {:?}", e);
        poem::Error::from_status(StatusCode::from_u16(500).unwrap())
    })
```

but it renders as `text/plain` and there's nothing in the docs about response types.

**Comment by sunli829** [comment]
You need to specify a status code for each error, like this:

```rust
use poem::error::InternalServerError;

TEMPLATES.render("index.html.tera", &context).map_err(InternalServerError)
```

**Comment by alper** [comment]
Ah I wasn't aware that thing existed that you can just throw into `map_err`.

**Comment by alper** [comment]
OK. Then to turn it into HTML, I did this:

```rust
TEMPLATES
    .render("index.html.tera", &context)
    .map_err(InternalServerError)
    .map(Html)
```
