### ISSUE TITLE
Changing OneOf to Union breaks semver

### ISSUE THREAD

**Issue by bbqsrc** [poem-web/poem#169]
## Expected Behavior

`OneOf` still works and is marked as deprecated. Please make it an alias of `Union`. Same with the `oai` field `property_name`, which now seems to be `discriminator_name`.

Alternatively, bump the major version. 🙂 

## Actual Behavior

Build errors.

## Steps to Reproduce the Problem

1. Build anything using OneOf after updating to the most recent version, haha.

## Specifications

- Version: 1.2.36
- Platform:
- Subsystem:

**Comment by sunli829** [comment]
This is a small change. 😂

**Comment by sunli829** [comment]
In fact, the previous implementation of `OneOf` was not correct, so I refactored it, and now it is `any_of` by default, unless the `one_of` attribute is specified, which will lose some performance.

**Comment by bbqsrc** [comment]
I understand, but that's why I'm suggesting deprecating it in code so instead of a build error, I get angry warnings to change.

Once the API is public, changes like this will break stuff in production and we don't always have time to fix these small things when trying to fix other things. This is what semver guarantees are for: if a change would break the build, it should be a major version bump. I have no problem with it being a major version bump and using poem-openapi v582.0.1 in 2 weeks time, I just like knowing that when a patch version increments it's not going to break the build, hehe. :)

**Comment by bbqsrc** [comment]
Aha, I see. If it is a breaking change due to being incorrect, then it's a valid break but the migration path should be documented in the change log to simplify the process. I had to read the commits to understand what to change. :D

**Comment by sunli829** [comment]
So the previous name `OneOf` was not suitable, and now non-object members can be supported:

```rust
#[derive(Union)]
struct MyObj {
     A(i32),
     B(ObjB), // <<--- a object
}
````

**Comment by sunli829** [comment]
I'm so sorry, I really don't want to make breaking changes. 😂

**Comment by bbqsrc** [comment]
Proposed changes are in https://github.com/poem-web/poem/pull/170 :)

**Comment by sunli829** [comment]
Thank you  so much! 😀

**Comment by sunli829** [comment]
I must say that `discriminator_name` is no longer a required parameter now.

**Comment by bbqsrc** [comment]
Nice. :)

**Comment by sunli829** [comment]
But if `discriminator_name` exists, it will improve parsing performance.
