### ISSUE TITLE
Regex for CORS whitelist

### ISSUE THREAD

**Issue by wileybaba** [poem-web/poem#172]
Is it possible to use a regular expression to whitelist a group of domains that match a certain pattern? 

Something like `Cors::new().allow_origin(Regex::new(r"[a-zA-Z]\.mydomain\.vercel\.app").unwrap());`

**Comment by sunli829** [comment]
Of course, you can use [method.allow_origins_fn](https://docs.rs/poem/1.2.38/poem/middleware/struct.Cors.html#method.allow_origins_fn).

**Comment by wileybaba** [comment]
Perfect 👍 

For anyone looking for a usage example:
```rust
fn allowed_staging_origins(origin: &str) -> bool {
  let re = Regex::new(r"https://*?.stagingdomain.com/?"
}

Cors::new().allow_origins_fn(allowed_staging_origins)
```
