### ISSUE TITLE
OpenAPI: Rust docs on "Object" annotated struct are converted to title; should be summary

### ISSUE THREAD

**Issue by kevinbader** [poem-web/poem#173]
## Expected Behavior

Triple-slash documentation should always be rendered as a summary, so it shows up in the API documentation.

## Actual Behavior

For methods the documentation is rendered as a "summary", but for structs (`Object`) it is rendered as a "title". How this affects the UI:

- RapiDoc doesn't show the comments at all
- Swagger UI shows an awkwardly formatted text in the schema view
- Redoc renders the title in parenthesis next to the type, which is labeled `integer <uint64>` (which is wrong, cause the body is an object - see the example below)

## Steps to Reproduce the Problem

Here's some example code to reproduce the problem (sorry that it's not super minimal):

```rust
use poem::{listener::TcpListener, Route};
use poem_openapi::{payload::Json, Object, OpenApi, OpenApiService};
use serde::{Deserialize, Serialize};

/// This is a Foo object used for requests to /foo.
#[derive(Deserialize, Object)]
#[oai(inline, rename_all = "camelCase", example = "Foo::default")]
struct Foo {
    /// The foo value is ancient wisdom. Must not be OVER 9000!!!
    #[oai(validator(maximum(value = 9000.)))]
    the_foo_value: usize,
}

impl Default for Foo {
    fn default() -> Self {
        Self { the_foo_value: 42 }
    }
}

/// This is a Bar object used for responses to requests to /foo.
#[derive(Serialize, Object)]
#[oai(inline, rename_all = "camelCase")]
struct Bar {
    /// The bar value is even more ancient and more wise.
    the_bar_value: usize,
}

struct Api;

#[OpenApi]
impl Api {
    /// Send a Foo, get a Bar.
    #[oai(path = "/foo", method = "post")]
    async fn foo(&self, foo: Json<Foo>) -> Json<Bar> {
        Json(Bar {
            the_bar_value: foo.the_foo_value + 1,
        })
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let name = env!("CARGO_PKG_NAME");
    let version = env!("CARGO_PKG_VERSION");
    let description = env!("CARGO_PKG_DESCRIPTION");
    let api_service = OpenApiService::new(Api, name, version)
        .server("http://localhost:3000/api")
        .description(description);
    let app = Route::new()
        .nest("/", api_service.rapidoc())
        .nest("/spec", api_service.spec_endpoint())
        .nest("/swagger-ui", api_service.swagger_ui())
        .nest("/redoc", api_service.redoc())
        .nest("/api", api_service);

    poem::Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(app)
        .await
}
```

This is how this renders in RapiDoc:

![image](https://user-images.githubusercontent.com/1306829/150416506-b9453d42-4fd2-496c-a628-f531a50a1897.png)

Neither the comment on the struct, nor the comment on the field are rendered.

## Specifications

```bash
$ cargo --version
cargo 1.58.0 (7f08ace4f 2021-11-24)
$ rustc --version
rustc 1.58.0 (02072b482 2022-01-11)
$ uname
Darwin
```

```toml
[package]
edition = "2021"

[dependencies]
poem = { version = "~1.2.39", features = [
    "compression",
    "opentelemetry",
    "prometheus",
    "rustls"
] }
poem-openapi = { version = "1.2", features = [
    "swagger-ui",
    "rapidoc",
    "redoc"
] }
serde = { version = "~1.0.133", features = ["derive"] }
serde_json = "~1.0.75"
tokio = { version = "1.15.0", features = ["full"] }
```

**Comment by sunli829** [comment]
I updated the `master` branch, would you please help me to test if it has been fixed. @kevinbader

**Comment by kevinbader** [comment]
Hi @sunli829 , thanks, that was quick :) Here are the results.

# Swagger UI

The description now renders properly for the schema, for both the struct and the field:

![image](https://user-images.githubusercontent.com/1306829/150506455-6b16a5f9-5472-489e-b3eb-d8e595c529c8.png)

# RapiDoc

The description renders fine here too. One nuisance is that the field description is not visible by default but only after clicking on "Multiline description". Of course that might be related to RapiDoc rather than poem..

![image](https://user-images.githubusercontent.com/1306829/150506857-2c299342-a5b2-48c3-91a7-acde9f6fcb03.png)

![image](https://user-images.githubusercontent.com/1306829/150506918-a8e88049-9295-4a11-8601-8b99bc2e9177.png)

So unless the "multiline description" option can be enabled by default through poem, I'd consider this bug resolved :) Thanks!

**Comment by sunli829** [comment]
Yes, I have set the `schema-description-expanded` option to `true`.
