### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by JinAirsOs** [poem-web/poem#18]
When I first to use poem, I copied the examples, and cargo run. It looks like this.
How to solve it? v0.4.5
<img width="894" alt="截屏2021-08-31 下午7 58 45" src="https://user-images.githubusercontent.com/18346465/131498581-3a6bc339-45e2-4c9e-aebd-58188a0e9f71.png">

**Comment by sunli829** [comment]
You should upgrade Rust to 1.54.😄
