### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JinAirsOs** [poem-web/poem#19]
The example looks like this.
`use poem::{handler, route, web::Path, RouteMethod, Server};

#[handler]
fn hello(Path(name): Path<String>) -> String {
    format!("hello: {}", name)
}

#[tokio::main]
async fn main() {
    let app = route().at("/hello/:name", RouteMethod::new().get(hello));
    let server = Server::bind("127.0.0.1:3000").await.unwrap();
    server.run(app).await.unwrap();
}`
but i think like this below is nice.
`use poem::{handler, route, web::Path, RouteMethod, Server};

#[handler]
fn hello(Path(name): Path<String>) -> String {
    format!("hello: {}", name)
}

#[tokio::main]
async fn main() {
    let app = route().get("/hello/:name", hello);
    let server = Server::bind("127.0.0.1:3000").await.unwrap();
    server.run(app).await.unwrap();
}`

this is easy to understand and write and more friendly to users. I think.

**Comment by JinAirsOs** [comment]
let app = route().get("/hello/:name", hello);
instead of 
let app = route().at("/hello/:name", RouteMethod::new().get(hello));

**Comment by sunli829** [comment]
Well, it looks good, but it is not easy to support chain calls, such as the following, what do you think?

```rust
let app = route().at("/", RouteMethod::new().get(a).post(b));
```

**Comment by JinAirsOs** [comment]
I come from golang，in golang famous web framework, such as gin, 
<img width="717" alt="截屏2021-09-01 上午11 30 36" src="https://user-images.githubusercontent.com/18346465/131607294-f2e5bfb4-3cfe-422b-96bc-9804f5cec499.png">
or in other gc languages, this is common.
But rust has no gc, so i don't know if it is too difficult to imply this. Simple is beautiful. But if it is too difficult to imply, i think it's fine.

**Comment by sunli829** [comment]
I think Rust has a special API design criterion, which is as different from Go as the difference between Poem and Gin. 😁

**Comment by umaYnit** [comment]
how about this:
```rust
let route = route().at("/").get(a).post(b));
```
