### ISSUE TITLE
Ability to get structured information about OpenAPI validation errors

### ISSUE THREAD

**Issue by vimmerru** [poem-web/poem#195]
## Description of the feature

Now ParseParamError, ParseJsonError contains information about error only as string that can't be parsed on client side to display field level errors.

It would be nice to have something like this in error chain

https://docs.rs/validator/latest/validator/struct.ValidationErrors.html

```rust
 let body = ErrorResponse {
            kind: self.kind.to_string(),
            message: self.to_string(),
            errors: self
                .source
                .chain()
                .map(|e| e.to_string())
                .collect::<Vec<_>>(),
            validaton_errors: self
                 .source
                 .downcast_ref::<validator::ValidationErrors>()
                .map(|e| e.errors()),
        };
 ```

**Comment by Christoph-AK** [comment]
+1 for better validation results. I would love to somehow have better messages aswell, maybe containing the field in which the parse error occured. Now I normally just get "Null found, expected Number!" without knowing WHERE that occured.
