### ISSUE TITLE
Create apis service macro `OpenApi` without redefining all structs

### ISSUE THREAD

**Issue by fmassot** [poem-web/poem#201]
First of all, thanks for all the work done here, it seems very promising and we want to use it for [Quickwit](https://github.com/quickwit-inc/quickwit)

My use case is the following: I have some complex struct in our project and I want to reuse them without much effort in the API services I want to create.

Basically I have: and external complex struct `IndexMetadata` and I want to create the following service:

```rust
#[OpenApi]
impl IndexesApi {
    #[oai(path = "/indexes", method = "post")]
    async fn create(
        &self,
        metastore: Data<&Arc<dyn Metastore>>,
        description: Json<IndexMetadata>,
    ) -> Result<Json<String>> {
        Ok(Json("OK".to_string()))
    }
    
    #[oai(path = "/indexes/:id", method = "get")]
    async fn get(&self, metastore: Data<&Arc<dyn Metastore>>, id: Path<String>) -> Result<Json<IndexMetadata>> {
      // Retrieve index metadata from metastore
      let index_metadata = metastore.index_metadata(&id)
        .await
        .map(|metadata| {
            Json(metadata)
        })
        .map_err(|error| ApiError::NotFound)?;
      Ok(Json(index_metadata))
    }
}
```

But as you know, it is not working as I need `IndexMetadata` to implement `ToJSON` and `Type` traits. I can wrap `IndexMetadata` in `IndexMetadataObject` and implement these traits for this new struct but... I'm wondering if it's possible to make it simpler.

Thanks!

**Comment by sunli829** [comment]
I am so happy that Quickwit is willing to try Poem. 😁

The `IndexMetadataObject` structure needs to be redefined for OpenApi due to limitations of procedural macros, but I can make it simpler.

```rust
#[derive(Object)]
#[oai(remote = "crate::internal:: Resource")]
struct Resource {
    value1: i32,
    value2: String,
}
```

After specifying the remote attribute, I can get it to help implement `From<crate::internal:: Resource>` and `Into<crate::internal:: Resource>`.

It works like this: https://serde.rs/remote-derive.html

What do you think?

**Comment by fmassot** [comment]
Ok, this is interesting but I have nested structs and this means I would have to redefine all the structs here.

The general use case would be: is it possible to have a #[derive(Object)] that works with serializable/deserializable structs?

I tried to wrap my original struct into a new one with a `rename_all = "camelCase"` as I need that:
```rust
#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct IndexMetadataObject {
    #[serde(flatten)]
    pub inner: IndexMetadata,
}
```

I tried to use it but I need to do more stuff to make it work and it seems not trivial for me :)

**Comment by sunli829** [comment]
This doesn't work, the `Object` macro needs to get all the structure information, you can only redefine all the structures. 🙂

**Comment by sunli829** [comment]
You can use `poem::types::Any<T>`, but this will lose all field information of the structure.
