### ISSUE TITLE
Add EventStream for event containing bytes

### ISSUE THREAD

**Issue by fmassot** [poem-web/poem#202]
## Description of the feature

Currently, it's possible to return a stream of events that are text event. Is it possible to support stream of bytes?

## Use case

For [quickwit](https://github.com/quickwit-oss/quickwit/), we need to return a stream of bytes, see this [example](https://quickwit.io/docs/guides/add-full-text-search-to-your-olap-db/).

## Code example

```rust
pub struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/events", method = "get")]
    async fn index(&self) -> EventStream<BoxStream<'static, Binary<Vec<u8>>>> {
        EventStream::new(Box::pin(
            async_stream::stream! {
                for i in 0..20 {
                    tokio::time::sleep(Duration::from_secs(1)).await;
                    yield Binary(vec![1,2,3]);
                }
            })
        )
    }
}
```

**Comment by sunli829** [comment]
AKAIK SSE doesn't support binary transfer, I guess you want to be able to encode binary in `base64`?

**Comment by sunli829** [comment]
If you are referring to [this](https://quickwit.io/docs/reference/rest-api/#search-stream-in-an-index), then you should use `Binary<Body>`.

```rust
Binary(Body::from_async_reader(...))
```

**Comment by fmassot** [comment]
Yes `Body::from_async_reader(...)` should do the job! thanks!
