### ISSUE TITLE
Can't fill in examples in rapidoc when using Oneof types

### ISSUE THREAD

**Issue by saintazunya** [poem-web/poem#203]
Hi, First of all, thanks for all the work done.
I recently found some issues when using the Oneof types: I can't fill in an example on the rapidoc ui.
## Expected Behavior
developer should be able to choose and fill an example request on ui

## Actual Behavior
<img width="199" alt="Screen Shot 2022-02-14 at 9 45 17 PM" src="https://user-images.githubusercontent.com/23186189/153999984-02489163-324f-4d52-9c40-8746612df448.png">
can do nothing here

## Steps to Reproduce the Problem
a slight change in examples can reproduce this issue

```rust
use poem::{listener::TcpListener, Route, Server};
use poem_openapi::{payload::Json, Object, OpenApi, OpenApiService, Union};

#[derive(Object, Debug, PartialEq)]
struct A {
    v1: i32,
    v2: String,
}

#[derive(Object, Debug, PartialEq)]
struct B {
    v3: f32,
}

#[derive(Union, Debug, PartialEq)]
#[oai(one_of = true, discriminator_name = "type")]
enum MyObj {
    A(A),
    B(B),
}

struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/put", method = "post")]
    async fn index(&self, obj: Json<MyObj>) -> Json<MyObj> {
        obj
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "poem=debug");
    }
    tracing_subscriber::fmt::init();

    let api_service = OpenApiService::new(Api, "Union", "1.0").server("http://localhost:3000/api");
    let ui = api_service.rapidoc();
    let spec = api_service.spec_endpoint();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(
            Route::new()
                .nest("/api", api_service)
                .nest("/", ui)
                .at("/spec", spec),
        )
        .await
}


```

## Specifications

- Version:  poem-openapi = { version = "1.2.56", features = ["rapidoc"] }
- Platform: ProductName:	macOS ProductVersion:	12.0.1 BuildVersion:	21A559
- Subsystem:

**Comment by sunli829** [comment]
I also don't understand why this is happening, it looks like the generated spec is correct. 😂

**Comment by sunli829** [comment]
I hope someone will tell me why. 🙂

**Comment by Christoph-AK** [comment]
There a some validators e.g. at https://apitools.dev/swagger-parser/online/ or https://editor.swagger.io/ (which funnily show some errors for the poem-generated spec, in my case they complain about an `externalDocs: null` that isn't supposed to be included, if null, and the `summary` being non standard, but probably I just made a mistake somewhere.)

Maybe some of these point out a mistake somewhere?

**Comment by sunli829** [comment]
@Christoph-AK  Thanks a lot, this tool definitely helps me.

**Comment by sunli829** [comment]
I verified a project of my own, which uses almost all the functionality of `poem-openapi`, generated about 10,000 lines of spec, and found no other errors except `externalDocs`. 🙂
