### ISSUE TITLE
poem-openapi-docs: please support documentation generation

### ISSUE THREAD

**Issue by colemickens** [poem-web/poem#204]
## Description of the feature

Hi! I'm very excited about poem and its openapi facilities. I've looked around at openapi resources and it seems that:

1. All of them seem to require JS for a decent/basically working experience.
2. All of them are ... not written in Rust.

It would be great if there were a `poem-openapi-docs` that would:

1. Build time compile openapi specs into static HTML files that do not require javascript.
2. Support passing a URL to an openapi spec (considering security implications, maybe a domain whitelist with special attention to url parsing/handling)
3. (future): Support progressive enhancement of the documentation page with {rust-wasm-framework-thats-popular} to add support for making API requests from doc page in the browser

**Comment by sunli829** [comment]
I'm sure it would take a lot of work and wouldn't make much sense. 🙂

**Comment by colemickens** [comment]
I did find these things, which made me think this idea wasn't totally off the wall:

1. https://crates.io/crates/utoipa - derive from structs, but ultimately just uses swagger-ui (there are others like this, and I see that poem-openapi has this too)
2. https://github.com/sourcey/spectacle - seemingly static docs with light js-enhancement; not Rust; not sure how it would integrate with poem

**Comment by colemickens** [comment]
Ope, just saw your reply @sunli829 -- now that I see there's already swagger-ui support, I realize this would have... limited value to limited folks. I wanted to at least ask, but I of course understand if this is not prioritized and/or considered out of scope for poem "core".

**Comment by sunli829** [comment]
It looks like you want `Poem` to provide something like [spectacle](https://github.com/sourcey/spectacle), which I think would be pretty low priority. 🙂

**Comment by colemickens** [comment]
Thanks again for consideration. After a few weeks, I definitely don't really see the need for poem to have its own version. Rust everything is cool, but the openapi-generators project actually have several web-compatible (output) javascript-free solutions:

In case someone else winds up here, and for search engines, here are some options I found for static generation of openapi documentation with output that does not require javascript (aka "nojs" or "javascript-free") to consume.

These are links through gitcdn so that they render, but they're in the openapi-generators sample dir:
* html.md: https://min.gitcdn.link/cdn/OpenAPITools/openapi-generator/master/samples/documentation/html.md/index.html
* html: https://min.gitcdn.link/cdn/OpenAPITools/openapi-generator/master/samples/documentation/html/index.html
* **(best, imo) html2**: https://min.gitcdn.link/cdn/OpenAPITools/openapi-generator/master/samples/documentation/html2/index.html#api-Pet-addPet
* markdown: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/documentation/markdown/Apis/PetApi.md#addpet
