### ISSUE TITLE
add support with tokio-metrics

### ISSUE THREAD

**Issue by attila-lin** [poem-web/poem#206]
## Description of the feature

add a feature like `metrics` for makeing it easier for Tokio users to debug performance problems with their applications by providing visibility into runtime behaviors in production.

And it can be add when the `tokio-metrics` is stable.

## Code example (if possible)

I think the API can quit like `around`.

with the feature
```toml
features = ["metrics"]
```
and 

```rust
Route::new().at("/", get(index)).metrics();

.metrics_page("/metrics_page")

```

Then we will get the runtime behaviors in console or a new page.

**Comment by sunli829** [comment]
Added in `v1.3.16`
