### ISSUE TITLE
Multipart: invalid content type `multipart/form-data`, expect: `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by TanLiangZhong** [poem-web/poem#21]
![image](https://user-images.githubusercontent.com/30589592/132098037-e0fd591e-94ba-404b-bbe9-0b2ad00d74b7.png)

How to solve it，Failed to upload file 。 invalid content type `multipart/form-data`, expect: `application/x-www-form-urlencoded`

**Comment by sunli829** [comment]
Thank you, this is a bug, I have fixed it in `v0.4.9`. 🙂
