### ISSUE TITLE
Poem w/ Tonic doesn't return gRPC status header

### ISSUE THREAD

**Issue by Mcfloy** [poem-web/poem#212]
## Expected Behavior
As I am exposing a grpc API through Poem, I should be able to call it correctly with a tool like BloomRPC and make a quick test of the API, the tonic example is good as a reference for this ticket.

## Actual Behavior
BloomRPC doesn't know the status of the response, and can't establish if the request has been properly handled, when debugging with the client code from poem examples folder, I see that the Poem's version of the API doesn't return a  [grpc-status](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)  header that should returned.
## Steps to Reproduce the Problem

1. Clone the [tonic](https://github.com/poem-web/poem/tree/master/examples/poem/tonic) example.
2. Launch the server with `cargo run --bin example-tonic` 
3. Launch the client with `cargo run --bin example-tonic-client` 
4. Launch BloomRPC, add the proto from the example folder, update the address to the `localhost:3000` that has been set in the server config. 

## Specifications

- Version: Any version
- Platform: Ubuntu 20.04
- Subsystem: /

**Comment by sunli829** [comment]
Really fixed this time. 😁

**Comment by Mcfloy** [comment]
Works perfectly! Thank you very much! :clap:
