### ISSUE TITLE
Is it possible to have generic OpenApi?

### ISSUE THREAD

**Issue by vimmerru** [poem-web/poem#216]
I am trying to avoid direct dependency to business layer when expose API and struggling here.

In my business layer i have trait that defines api interface(+ some implementation). Like this

```rust
trait MyApiPort {
   type MyRepository: MyRepositoryPort;
   
   async fn some_call(&self, SomeCallRequest, repo: & MyRepository) -> Result< SomeCallResponse>;
}

pub struct MyApi<UserRepository> {
    _marker: PhantomData< MyRepository >
}

#[async_trait(?Send)]
impl<MyRepository: MyRepositoryPort> MyApiPort for MyApi< MyRepository > {
    type MyRepository = MyRepository;
    
    ...
}
```

Now i want to expose my api as OpenAPI with poem, but i want avoid direct dependency to MyApi struct and depend on MyApiPort instead

```rust
struct MyOpenApi<MyApi> {
    api: MyApi;
}

#[OpenApi(tag = "ApiTags::MyApi")]
impl<MyApi: MyApiPort> MyOpenApi<MyApi> {

    #[oai(path = "/some_call", method = "post")]
    async fn some_call(
        &self,
        req: Json< SomeCallRequest >,
        users: Data<& MyApi::MyRepository>,
    ) -> SomeResponse {
       ...
    }
}
```

Seems OpenApi can't work with generic impls as i getting error about unknown types. Is there any way to workaround this and be able to abstract and mock from business layer here?

**Comment by vimmerru** [comment]
One solution can be usage of trait objects, but i am trying avoid dynamic dispatch.

**Comment by sunli829** [comment]
Sorry for the late reply, it's been too busy at this time. 😂

I added support for generic `OpenAPI` in `v1.3.10`, here is the example:

https://github.com/poem-web/poem/blob/5f39209c25fc40e30e2ec7958284227daee939cd/poem-openapi/tests/api.rs#L622

**Comment by vimmerru** [comment]
@sunli829 Great, thank you.
