### ISSUE TITLE
Async-graphql and Poem, how to set a cookie on the client

### ISSUE THREAD

**Issue by wileybaba** [poem-web/poem#233]
Hi there!

I have a simple login mutation where I'm calling `ctx.insert_http_header(SET_COOKIE, token);` with a newly created JWT.

What do I have to do in my poem web server code to get this cookie to be set on the client by this resolver?

My async-graphql poem handler code can be found here: https://github.com/populist-vote/platform/blob/main/server/src/main.rs#L43

**Comment by sunli829** [comment]
You can use `async-graphql-poem` which does this for you.

If you want to do it yourself, you can refer to here:

https://github.com/async-graphql/async-graphql/blob/b82186413b0accdf9903a9a5b4256512d1a36fde/integrations/poem/src/response.rs#L40

**Comment by wileybaba** [comment]
Is there additional code that is needed to get `async-graphql-poem` to handle this? I'm using it and even with a simple resolver: 
 ```
async fn set_cookie(&self, ctx: &Context<'_>) -> Option<String> {
        ctx.insert_http_header("Set-Cookie", format!("testName=testValue"))
    }
```
the cookie is not being set in the response.

**Comment by wileybaba** [comment]
I was able to get it working by changing the response type to `async-graphql-poem::GraphQLResponse` and returning `schema.execute(req.0.data(token_data)).await).into()` instead of the `Json` return above.  poem + async-graphql 🚀
