### ISSUE TITLE
infer return type in openapi

### ISSUE THREAD

**Issue by xialvjun** [poem-web/poem#238]
## Description of the feature
I know rust doesn't have return type infer, we must write the complete function signature. But using poem-openapi, we write code in macros, so maybe it's possible to auto infer the handlers' returning type.

## Code example (if possible)

```rust
#[OpenApi]
impl Api {
    #[oai(path = "/getUsers", method = "get")]
    async fn getUsers(&self, pool: Data<&sqlx::Pool<sqlx::Sqlite>>) {
        let mut conn = pool.acquire().await?;
        sqlx::query!("select * from users")
            .fetch_many(&mut conn)
            .await?
    }
}
```

Of course I need to `impl IntoResponse for sqlxResponse` and `impl poemError for sqlxError`

**Comment by sunli829** [comment]
Procedural macros cannot do this. 😂
