### ISSUE TITLE
session relative API/examples like actix_session::Session?

### ISSUE THREAD

**Issue by pymongo** [poem-web/poem#24]
Is there any session example like <https://github.com/actix/examples/tree/master/session> ?

**Comment by sunli829** [comment]
Using the `CookieJar` extractor can be very easy, but there is no complete example yet.

Use it like below:

```rust
#[handler]
fn index(cookie_jar: &CookieJar) {
     let my_cookie = cookie_jar.get("mycookie"); // Get a cookie
     cookie_jar.add(Cookie::new(...)); // Set a new cookie
}
```

**Comment by sunli829** [comment]
We now have a complete example. #25
