### ISSUE TITLE
Improve Tokio Metrics

### ISSUE THREAD

**Issue by Christoph-AK** [poem-web/poem#240]
Hey, 
thanks for integrating tokio metrics!
In the current form using the cumulative monitor I don't think they are of much use tho. I have three points I'd like to discuss on this: 

1. Could we change the default output to a window of a second or maybe 5 seconds? That way by frequently polling we can keep a track of the performance at specific times. If people want, they can still accumulate the data points in a consumer.
2. Can we somehow reformat the output to correct json? 
3. Can we maybe add a dynamic system that adds a new monitor for every new endpoint it encounters? Seems non trivial to implement for me as I don't now if we can somehow find out to which endpoint some request will be forwarded from within the middle ware, but might be interesting to find out which endpoints have the most performance impact.

I am currently creating a simple UI for this, maybe I'll PR that one in as an endpoint similar to Swagger_UI once I'm happy with it.

I'll take a look at the first two, if anyone has experience in these matters, please feel free to chime in. 

Continuation of #206 , @attila-lin

**Comment by attila-lin** [comment]
Agree.

Add a UI for the result would be great!

**Comment by sunli829** [comment]
Following @Christoph-AK's suggestions, I improved the `TokioMetrics` middleware in the `master` branch.

**Comment by Christoph-AK** [comment]
@sunli829 Thanks for looking into this!

With the current version I can't seem to find a way to access the data 😅

I guess in the best case we had a 'metrics_summary' endpoint that gives a cumulated summary of all running monitors (Sum of 'times and counts'-stats, maximum of the 'highest time'-stats), and a 'metrics_details' endpoint that lists all monitors separately.

**Comment by Christoph-AK** [comment]
Working nicely so far! 

As I said I'm unfortunately horrible at everything frontend related, but got some basic monitoring running (sum of all endpoint calls):

![grafik](https://user-images.githubusercontent.com/72923608/159284505-792c7003-e3e7-4ecd-9dcf-20817d0a3705.png)

Funnily the browser does make a call to /favicon that gets 404ed, so every page refresh counts as at least 2 requests. 

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tokio Metrics</title>
        <!-- <link rel="stylesheet" href="./style.css"/> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"
            integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- <script src="lib.js" defer></script> -->
    </head>
    <body style="background: #333; color: #ddd;">
        <canvas id="myChart" style="max-height: 300px;"></canvas>
        <script>
            const ctx = document.getElementById('myChart');

                const arrayLength = 100;
                const refreshTime = 5000;
                const url = "http://localhost:3000/metrics";

                Array.prototype.push_rotating = (function (element, limit) {
                    if (this.length < limit) {
                        this.push(element)
                    } else {
                        this.shift();
                        this.push(element);
                    }
                })

                let data = [];

                let i = 0;

                for (let j = -arrayLength; j < 0; j++) {
                    data.push({
                        time: j * (refreshTime / 1000.0),
                        ping: null
                    })
                }

                let add_fetching = (async function () {
                    let new_count = await fetch(url).then(response => {
                        if (!response.ok) {
                            throw new Error('Network response was not OK');
                        }
                        return response.json();
                    }).then(body => {

                        console.log(body);

                        let count = 0;
                        for (let i in body) {
                            count += body[i]["instrumented_count"];
                        }

                        return count
                    });
                    console.log(new_count);
                    data.push_rotating({
                        time: i,
                        ping: new_count
                    }, arrayLength);
                    i += refreshTime / 1000.0;
                    console.log(i);
                    console.log(data);
                    console.log(data.map(o => o.time));
                    console.log(data.map(o => o.ping));
                })

                const myChart = new Chart(ctx, {
                    type: 'line',
                    options: {
                        scales: {
                            x: {
                                ticks: {
                                    display: false
                                }
                            }
                        }
                    }
                });

                let update_chart = (function () {
                    myChart.data = {
                        labels: data.map(o => o.time),
                        datasets: [{
                            label: 'RequestCount',
                            data: data.map(o => o.ping),
                            borderColor: "rgb(155, 102, 102)",
                            backgroundColor: "rgb(155, 102, 102)",
                        }]
                    };
                    myChart.update('none')
                });

                update_chart();

                var t = setInterval(function () {
                    add_fetching();
                    update_chart()
                }, refreshTime);

                add_fetching();
        </script>
    </body>
</html>
```

**Comment by sunli829** [comment]
It looks pretty good👏🏻, I'll improve this later and embed the UI in poem.

**Comment by Christoph-AK** [comment]
I thought about the performance impact of the current implementation tho. A new monitor gets instantiated for each unique URI, meaning `people/1` and `people/2` each get their own monitor running, potentially meaning thousands of new monitors per second. Is this okey, especially with the locking going on with each request? Maybe we could make the 'simple' implementation with only 1 monitor available optionally. Changing this at startup time should be okey initially.

**Comment by sunli829** [comment]
I improved again. 😂 @Christoph-AK
