### ISSUE TITLE
Please adhere to semantic versioning 

### ISSUE THREAD

**Issue by AzureMarker** [poem-web/poem#246]
This project has been called out for breaking semver before:
* https://github.com/poem-web/poem/issues/146
* https://github.com/poem-web/poem/issues/169
* https://github.com/poem-web/poem/issues/200

Taking a look at the [changelog](https://github.com/poem-web/poem/blob/a7aad2b096384fc91cb01251513d2f6d17f33149/poem/CHANGELOG.md), there are numerous examples of breaking changes, including renaming/moving functions and types, moving existing code to be behind feature flags, removing types, etc.

From the amount of breaking changes and the response in the previous issues, I'm not sure if this problem is being taken seriously. People are using this library in production, and the version is past 1.0, so being this cavalier about breaking changes is a red flag.

Please follow the guidelines in https://doc.rust-lang.org/cargo/reference/semver.html, https://rust-lang.github.io/rfcs/1105-api-evolution.html, and https://semver.org/spec/v2.0.0.html. The Rust ecosystem relies on people to follow these guidelines to avoid breaking downstream user code (like in the linked issues).

## Expected Behavior
Upgrading from 1.0.8 to latest 1.x.x version does not break my code. This is explicitly called out and promised in the changelog:
https://github.com/poem-web/poem/blob/a7aad2b096384fc91cb01251513d2f6d17f33149/poem/CHANGELOG.md?plain=1#L5

## Actual Behavior
There were multiple breaking changes made between minor and even patch versions. This project does not adhere to semantic versioning.

## Steps to Reproduce the Problem
See for example the work done in this PR, to upgrade from 1.0.8: https://github.com/pyros2097/rust-embed/issues/173

## Specifications
N/A

**Comment by sunli829** [comment]
It won't happen again. 😂
