### ISSUE TITLE
Support chrono NaiveDate in OpenApi Object

### ISSUE THREAD

**Issue by eiswind** [poem-web/poem#252]
## Description of the feature
We tried to use a postgres DATE type, that maps to chrono NaiveDate in tokio postgres.
Unfortunately this is not supported in the Object derive.

We did workaround using a timestamptz/ DateTime<Utc> mapping. But it would be great if we had a date only there.

## Code example (if possible)

**Comment by sunli829** [comment]
Released in `v1.3.23`

**Comment by eiswind** [comment]
Thanks a lot. Works like a charm.
