### ISSUE TITLE
Consider lowering indexmap version requirement

### ISSUE THREAD

**Issue by jamesbirtles** [poem-web/poem#258]
I've run into https://github.com/tkaitchuck/aHash/issues/95 trying to include poem-openapi into my workspace. The workaround suggested in there is to pin indexmap to 1.6, but poem-openapi-derive requires 1.7. Seeing as 1.7 didn't introduce any new features, i suspect the requirement could be lowered in poem-openapi-derive which would solve this issue for me.

**Comment by sunli829** [comment]
Fixed `v1.3.25` 😁

**Comment by jamesbirtles** [comment]
amazing thanks!
