### ISSUE TITLE
poem-openapi doesn't get updated anymore 

### ISSUE THREAD

**Issue by glebpom** [poem-web/poem#260]
After #258 cargo update doesn't longer update `poem-openapi`. The version is always pinned to `1.3.24`

**Comment by sunli829** [comment]
I don't understand, is this caused by some rule of `cargo update`?

**Comment by glebpom** [comment]
It probably happens because other dependencies requier indexmap `1.7`, and choose the latest compatible version of `poem-openapi`

**Comment by sunli829** [comment]
I can't reproduce it, `cargo update` always upgrades `poem` to the latest version.

**Comment by glebpom** [comment]
Create a new project with the following `Cargo.toml`:
```
[package]
name = "test-poem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1"
poem-openapi = "1"
```

You will end up with the following `poem` dependencies installed:
```
    Checking poem v1.3.28
    Checking poem-openapi v1.3.24
```

If you remove `indexmap` from `Cargo.toml`, you will see `poem-openapi` gets upgraded:

```
➜  test-poem git:(master) ✗ cargo update
    Updating crates.io index
    Updating hashbrown v0.11.2 -> v0.9.1
    Updating indexmap v1.8.1 -> v1.6.2
    Updating poem-openapi v1.3.24 -> v1.3.28
    Updating poem-openapi-derive v1.3.24 -> v1.3.28
```

Putting it back again and running `cargo update` leads to the following:
```
    Updating crates.io index
    Updating hashbrown v0.9.1 -> v0.11.2
    Updating indexmap v1.6.2 -> v1.8.1
    Updating poem-openapi v1.3.28 -> v1.3.24
    Updating poem-openapi-derive v1.3.28 -> v1.3.24
```
