### ISSUE TITLE
Configure a global middleware in poem-openapi

### ISSUE THREAD

**Issue by ufoscout** [poem-web/poem#270]
I would like to configure some global middlewares (e.g. [Tracing](https://github.com/poem-web/poem/blob/master/poem/src/middleware/tracing_mw.rs) and [Opentelemetry](https://github.com/poem-web/poem/blob/master/poem/src/middleware/opentelemetry_tracing.rs) ) to my poem-openapi server.
The only example I found is [this one](https://github.com/poem-web/poem/blob/master/examples/openapi/poem-middleware/src/main.rs); but, in that case, the middleware is set on a specific path while I need to configure it for all paths in the application.
Could you please advise me on how to achieve it?

**Comment by crc-sstubbs** [comment]
I would also like to know how to do this.

**Comment by sunli829** [comment]
Sorry for late response, `OpenApiService` also implements `Endpoint`, which can be wrapped by `middleware` like this:

```rust
    let api_service =
        OpenApiService::new(Api, "Hello World", "1.0").server("http://localhost:3000/api");
    let ui = api_service.swagger_ui();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(
            Route::new()
                .nest("/api", api_service.with(Tracing)) // <<------
                .nest("/", ui),
        )
        .await
```
