### ISSUE TITLE
Possible to use relative paths with OAuth?

### ISSUE THREAD

**Issue by l1npengtul** [poem-web/poem#278]
Is it possible to use relative paths like this (or a custom `checker` function)?
```
#[derive(SecurityScheme)]
#[oai(
    type = "oauth2",
    flows(authorization_code(
        authorization_url = "/authorize",
        token_url = "/proxy",
        scopes = "GithubScopes"
    ))
)]
```

**Comment by sunli829** [comment]
Is it because your server supports OAuth2?

**Comment by l1npengtul** [comment]
Yes, I am using oxide auth to make my own OAuth provider and was wondering if poem openapi can plug directly into that.
