### ISSUE TITLE
static-files Preview Chinese garbled

### ISSUE THREAD

**Issue by TanLiangZhong** [poem-web/poem#28]
## Steps to Reproduce the Problem
![image](https://user-images.githubusercontent.com/30589592/133714860-97877571-ecdc-410f-974e-f44db298df7b.png)
![image](https://user-images.githubusercontent.com/30589592/133714889-181a3917-8e81-44d2-b813-87c183922918.png)

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by sunli829** [comment]
Because the response header does not give the correct `Content-Type`, I will add this feature later.

**Comment by sunli829** [comment]
Fixed in `v0.6.5`
