### ISSUE TITLE
error: generator cannot be sent between threads safely

### ISSUE THREAD

**Issue by easykoala** [poem-web/poem#281]
error: generator cannot be sent between threads safely

#[handler]
| ^^^^^^^^^^ future created by async block is not Send
|
= help: within RBatisTxExecutor<'_>, the trait Sync is not implemented for NonNull<libsqlite3_sys::bindings::sqlite3>
= note: required for the cast to the object type dyn Future<Output = Result<poem::Response, poem::Error>> + Send
= note: this error originates in the attribute macro handler (in Nightly builds, run with -Z macro-backtrace for more info)

coding:

///select page must have '?:&PageRequest' arg and return 'Page<?>'
#[html_sql("mapping/example.html")]
async fn select_by_condition(rb: &mut RbatisExecutor<', '>, page_req: &PageRequest, name: &str, shop_id: &i64) -> Page { impled!() }

// poem web frame
#[handler]
pub async fn list(state: Data<&AppState>, Query(params): Query) -> Result {
let page_no = params.page.unwrap_or(1);
let nums_per_page = params.pageSize.unwrap_or(DEFAULT_NUMS_PER_PAGE);
let rb = &state.rb;
println!("rb.clone {:?}", &rb);
rb.link(DBURL)
.await
.unwrap();

let page = select_by_condition(&mut rb.as_executor(), &PageRequest::new(1, 10), "", &100000010000000i64)
    .await
    .unwrap();

## Specifications

- Version: poem 1.3.30 rbatis 3.1.10
- Platform: windows 10
- Subsystem:

**Comment by sunli829** [comment]
It's not Poem's bug.
