### ISSUE TITLE
Need to input all data of every field?

### ISSUE THREAD

**Issue by easykoala** [poem-web/poem#282]
#[crud_table]
#[derive(Clone, Debug)]
pub struct BizActivity {
    pub id: Option\<String>,
    pub name: Option\<String>,
    pub sort: Option\<String>,
    pub status: Option\<i32>,
    pub version: Option\<i32>,
}

#[handler]
pub async fn biz_activity_create(state: Data<&AppState>, form: Form\<BizActivity>,) -> Result<impl IntoResponse> {
    println!("form: {:?}", &form.0);
    let rb = &state.rb;
    let r = rb.save(&form.0, &[]).await;
    if r.is_err() {
        println!("{}", r.err().unwrap().to_string());
    }
    Ok(StatusCode::FOUND.with_header("location", "/biz_activity"))
}

When only name field is entered, an error is returned：
url decode: cannot parse integer from empty string

**Comment by sunli829** [comment]
Is your code missing something?

**Comment by easykoala** [comment]
<form action="/biz_activity" method="post">
                <div class="twelve columns">
                    <input type="text" placeholder="id" name="id" id="id" value=""  autofocus class="u-full-width"/>
                    <input type="text" placeholder="name" name="name" id="name" value=""  autofocus class="u-full-width"/>
                    <input type="text" placeholder="pc_link" name="pc_link" id="pc_link" value=""  autofocus class="u-full-width"/>
                    <input type="text" placeholder="h5_link" name="h5_link" id="h5_link" value=""  autofocus class="u-full-width"/>
                    <input type="text" placeholder="sort" name="sort" id="sort" value=""   autofocus class="u-full-width"/>
                    <input type="text" placeholder="status" name="status" id="status" value=""  autofocus class="u-full-width"/>
                    <input type="text" placeholder="version" name="version" id="version" value=""   autofocus class="u-full-width"/>
                </div>
                <div class="twelve columns">
                    <div class="eight columns"></div>
                    <div class="two columns">
                        <input type="submit" value="save post"/>
                    </div>
                </div>
            </form>

**Comment by easykoala** [comment]
let app = Route::new()
        .at("/biz_activity/new", biz_activity::biz_activity_new)
        .at("/biz_activity", post(biz_activity::biz_activity_create))
        .nest(
            "/static",
            StaticFilesEndpoint::new(concat!(env!("CARGO_MANIFEST_DIR"), "/static")),
        )
        .data(state);
    let server = Server::new(TcpListener::bind(format!("{}:{}", host, port)));
    server.run(app).await

That's all.

**Comment by easykoala** [comment]
When all fields are entered, it is OK.

**Comment by sunli829** [comment]
You should remove the `status` and `version` parameters, `status=` means that the `status` parameter exists and is an empty string.

**Comment by sunli829** [comment]
Remove them from the query string.

`id=&name=22cedfr&pc_link=&h5_link=&sort=`

**Comment by sunli829** [comment]
https://github.com/nox/serde_urlencoded/issues/36

**Comment by sunli829** [comment]
```
An empty string isn't a missing value, I don't plan to change this.
```
