### ISSUE TITLE
poem.rs down?

### ISSUE THREAD

**Issue by jfaust** [poem-web/poem#283]
I found a link to https://poem.rs here: https://www.reddit.com/r/rust/comments/r4jzo3/poemopenapi_10_released/

That site seems to be down.

**Comment by sunli829** [comment]
Yes, moved the guides all into the source code since I didn't have enough time to maintain it. 🙂

**Comment by jfaust** [comment]
Ahh, got it. Was wondering why it wasn’t linked from anywhere else 🙂
