### ISSUE TITLE
How should I use `response_header` parameter in `OpenApi` services or `oai` handler?

### ISSUE THREAD

**Issue by windoze** [poem-web/poem#284]
According to the [doc](https://docs.rs/poem-openapi/latest/poem_openapi/attr.OpenApi.html), I can only set the name and type of the header, but the doc tells nothing about how to set its value.

**Comment by windoze** [comment]
Here is the thing, I've an OpenApi service with many APIs, each of them have different response schema, so either SwaggerUI and OpenAPI spec can work.
```
struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/hello", method = "get"]
    async fn hello(&self) -> poem::Result<Json<HelloResponseType>> { ... }

    #[oai(path = "/world", method = "get"]
    async fn world(&self) -> poem::Result<Json<WorldResponseType>> { ... }
}
```
By using `ApiResponse` I've to define one enum for **each** API, with redundant error responses in everyone of them, but if I mix all API response types in one enum, it will mess up the OpenAPI spec.

Seems that `Response<Json<SomeSchema>>` is the only viable solution here.

It'll be great if there is any way to use `oai` macro with flexible header generation mechanism.

Thanks for your help.

**Comment by sunli829** [comment]
You can use `ApiResponse` to customize error types so that they can be reused.

https://github.com/poem-web/poem/blob/3bd9ee79e94b3f8a088a21e16648e7be6eed471c/poem-openapi/tests/response.rs#L429

**Comment by stdlout** [comment]
Sorry to add to this closed issue, but are there any tutorials (or docs, but I scanned the official) for ApiResponse deriving and all the relevant attributes (such as this oai(header))?  I was struggling to find exactly this solution, it's not always obvious for newcomers and scanning tests to find methods of achieving something is pretty rough.
