### ISSUE TITLE
[docs] add comparison with other web frames, esp. axum

### ISSUE THREAD

**Issue by futurist** [poem-web/poem#29]
Is it possible to add a section in docs about the comparison with other web frames, esp. axum, I found they share lots of similarities in syntax, but the comparison can go more deeper and wider besides only the syntax?

**Comment by sunli829** [comment]
Poem and Axum look very similar, but the internal implementation is very different, as a contributor to Axum, I am very familiar with Axum, so the interface definition has some reference, but I do not currently have the idea of comparing other frameworks, continue to improve it is now the main work.
