### ISSUE TITLE
 is there a option to support redundant slash '/' in router?

### ISSUE THREAD

**Issue by youngsofun** [poem-web/poem#291]
i.e. auto remove empty path segment

e.g. https://github.com/datafuselabs/databend/issues/5960

seem not supported yet!

are you willing to support it in the future?

I see `normalize_path` but only used for  making endpoint with `nest`

some discussion
https://stackoverflow.com/questions/4659504/are-unnecessary-slashes-in-a-url-bad

> since the URL path is mostly used to be directly mapped onto the file system, web servers often remove empty path segments (Apache does that)

**Comment by sunli829** [comment]
You can use this middleware:

https://github.com/poem-web/poem/blob/50441dd27ffa6549da00adbaa5e5d598a9917dc0/poem/src/middleware/normalize_path.rs#L59
