### ISSUE TITLE
XML Support 

### ISSUE THREAD

**Issue by itsbalamurali** [poem-web/poem#296]
## Description of the feature

Add XML Support via Quick XML (Supports Serde): https://github.com/tafia/quick-xml on Poem & Poem OpenAPI.
## Code example (if possible)
Similar to current JSON support.

Really helpful in cases of dealing with SAML or other XML-based standards.

**Comment by sunli829** [comment]
Would you like provide a PR for this? 🙂

**Comment by itsbalamurali** [comment]
@sunli829 working on it. Will raise it.
