### ISSUE TITLE
2 sessions in a request

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem#300]
I would like to have 2 sessions in a single request, for example

1 session is normal login session.
2 session is some verification process, which should normally be much shorter.

I am not sure whether there is an easier way to do this with poem? as it seems like poem rely on single struct `Session`.

**Comment by sunli829** [comment]
I need to think about how to do it.

**Comment by phungleson** [comment]
Thanks for looking into this.

I was thinking of DIY but then poem session implementation is quite elegant, it makes more sense to find a way to extend it rather than dropping it.

**Comment by sunli829** [comment]
I need to find a more elegant solution. 🙂

**Comment by phungleson** [comment]
Hey @sunli829 just wonder if you come up with any ideas?

If it is not good enough to implement in poem, maybe I can do it in a separate crate. Cheers
