### ISSUE TITLE
Choose compression algorithms with priority

### ISSUE THREAD

**Issue by DCjanus** [poem-web/poem#301]
## Description of the feature
With middleware [Compression](https://docs.rs/poem/latest/poem/middleware/struct.Compression.html), response would be compressed if there is any algorithm specified in `Accept-Encoding` request header.

User agent may specified priority by this header like this: `Accept-Encoding: deflate, gzip;q=1.0, *;q=0.5`. But most browser would not specified priority for now.

For example, Header from Chrome would be like this: `accept-encoding: gzip, deflate, br`. And poem chose first algorithm, which means `gzip`. But usually, `Brotli` would perform better than `Gzip`, actual, all CDN that I know would chose `br` as most as they can.

Maybe we should specified default order for those algorithms, for example, `br gzip deflate`

**Comment by sunli829** [comment]
You are right, thanks for the PR.😃
