### ISSUE TITLE
WASM & Cloudflare Workers Support 

### ISSUE THREAD

**Issue by itsbalamurali** [poem-web/poem#303]
## Description of the feature
Support & Examples for WASM & Cloudflare Workers https://blog.cloudflare.com/workers-rust-sdk/

## Code example (if possible)
It can be done the same way as lambda integration.

**Comment by sunli829** [comment]
Since Cloudflare Workers are based on V8, maybe it won't be easy, but I'll try it later.

**Comment by oovm** [comment]
Has this been completed? Is there an example I can look at?

I'm trying to figure out the following conversion chain `http::Request -> poem::Request -> poem::Response -> http::Response`

**Comment by oovm** [comment]
Implementations of the `From` trait should be submitted upstream:

https://github.com/oovm/workers-rs/blob/078d15bb60d2b05af0236c7b1370f598f5e17ada/worker/src/http/response.rs#L101-L100

Then we can use this directly:

```rust
#[event(fetch)]
pub async fn fetch(req: HttpRequest, _env: Env, _ctx: Context) -> std::result::Result<HttpResponse, poem::Error> {
    let app = Route::new();
    Ok(app.call(req.into()).await?.into())
}
```
