### ISSUE TITLE
Add support for specifying `contact` field

### ISSUE THREAD

**Issue by banool** [poem-web/poem#306]
## Description of the feature
Currently there is no way to set the `contact` field of the OpenAPI spec (as far as I can tell from grepping the code). It would be great if we had:

1. The `contact` field is set automatically based on `Cargo.toml`.
2. The ability to override that with something you manually specify.

**Comment by sunli829** [comment]
Done! 🙂

**Comment by banool** [comment]
Awesome, thanks!
