### ISSUE TITLE
Add documentation for `oai` / improve discoverability

### ISSUE THREAD

**Issue by banool** [poem-web/poem#312]
Currently when you search for `oai` in the docs, nothing comes up: https://docs.rs/poem-openapi/latest/poem_openapi/?search=oai. This is one of the most important macros for the Poem OpenAPI crate but it's hard to figure out how to use it. Could we add documentation for it if it doesn't exist and an alias so you can search for it by `oai`?

**Comment by banool** [comment]
I see we have docs at `poem-openapi/src/docs/openapi.md`, we could make an alias to go search there at least.

**Comment by sunli829** [comment]
I don't know how to do it. 😂

**Comment by banool** [comment]
lol I can take a look at doing it, stay posted
