### ISSUE TITLE
How to return bytes but generate spec for specific type + encoding

### ISSUE THREAD

**Issue by banool** [poem-web/poem#314]
First, some code demonstrating what I want to do:

```
struct Api {
    db_handle: DbHandle
}

#[OpenApi]
impl Api {
    #[oai(path = "/get_stuff", method = "get", actual_type = Base64<Stuff>)]
    async fn get_stuff(&self) -> Binary<Vec<u8>> {
        self.db_handle.get_stuff()
    }
}
```

In short, I want to be able to read bytes from a DB and return them, but because I know they really represent a type (Stuff) encoded in a particular way (Base64), generate the OpenAPI spec in a way that says it returns Base64 encoded Stuff, not just a bunch of bytes.

Is there a way to do this today in Poem?

I want this to save myself having to deserialise Stuff just to reserialize it again.

Thanks!!

**Comment by sunli829** [comment]
```rust
struct Api {
    db_handle: DbHandle
}

#[OpenApi]
impl Api {
    #[oai(path = "/get_stuff", method = "get")]
    async fn get_stuff(&self) -> Base64<Vec<u8>> { // << just change this to Base64<Vec<u8>>
        self.db_handle.get_stuff()
    }
}
```

**Comment by sunli829** [comment]
You don't want to use `types::Base64` because its format is `string(bytes)` and you want `stuff(base64)`?

**Comment by sunli829** [comment]
I see, you want to return the binary directly from the database, thus avoiding unnecessary serialization, I'll add an `actual_type` attribute later.

**Comment by banool** [comment]
Awesome you're a legend.

**Comment by sunli829** [comment]
Is this what you want?

https://github.com/poem-web/poem/blob/cd27094b82bc07dfaf2cc87690b59a5cb4c7058d/poem-openapi/tests/api.rs#L675

**Comment by banool** [comment]
Yes that's exactly it, this would be very helpful for my use case.

**Comment by banool** [comment]
Actually on closer inspection, this doesn't quite do what I want. Apologies, it works for the example I gave, but I actually have a more complicated case:

```
#[derive(ResponseContent)]
pub enum MyResponseContent<T: ToJSON + Send + Sync> {
    // When returning data as JSON, we take in T and then serialize to JSON
    // as part of the response.
    Json(Json<T>),

    // When returning data as BCS, we never actually interact with the Rust
    // type. Instead, we just return the bytes we read from the DB directly, for
    // efficiency reasons. Only through the `schema` decalaration at the
    // endpoints does the return type make its way into the OpenAPI spec.
    // TODO: This `schema` / `actual_type` declaration doesn't exist yet
    #[oai(actual_type = "Bcs<T>")]
    Bcs(Bcs<Vec<u8>>),
}

#[derive(ApiResponse)]
pub enum MyResponse<T: ToJSON + Send + Sync> {
    #[oai(status = 200)]
    Ok(MyResponseContent<T>),
}
```

I imagine this is more complicated to add.

**Comment by sunli829** [comment]
```rust
#[derive(ResponseContent)]
pub enum MyResponseContent<T: ToJSON + Send + Sync> {
    Json(Json<T>),
    #[oai(actual_type = "Binary<T>")] // <<<< I'll add this
    Binary(Binary<Vec<u8>>),
}
```

**Comment by banool** [comment]
Awesome that would help a lot, because the solution above works but there is no type checking that the inner type is the same.

**Comment by sunli829** [comment]
Done! 🙂
