### ISSUE TITLE
Add example showing how to use custom `Path<T>` parameter

### ISSUE THREAD

**Issue by banool** [poem-web/poem#316]
None of the examples in the `examples/` dir today use a custom type in `Path`, they all just use existing types. It would be nice to demonstrate how users can user their own types. I would've thought that if a type impls `FromStr` that would be it, but that isn't enough.

Instead, you need to impl `ParseFromParameter`, which requires that the type impls `Type`. I suppose this makes sense, though all I'm doing currently to get around this is:

```
    async fn get_account(
        &self,
        address: Path<String>,
    ) -> Result<u64> {
        let address = Address::from_str(&address.0)?;
        ...
```

It feels like I should just be able to do `Path<Address>` even though `Address` doesn't impl `Type`, only `FromStr`. Perhaps there needs to be another trait that doesn't assume the value is `Type` but otherwise still has the two deserialization functions (one for just one value, one for an iterator).

**Comment by banool** [comment]
I can look at this myself when I have some spare time.

**Comment by banool** [comment]
@sunli829 what do you think about making it possible to have path params only need to impl `FromStr`? I believe warp works like this for example.

**Comment by banool** [comment]
Actually on second thought I suppose the issue here is it means the spec generation won't work, it won't know how to describe that param.

**Comment by sunli829** [comment]
If the path params only needs to implement `FromStr`, the necessary schema is missing.

**Comment by banool** [comment]
Yeah you're right, I'll close this issue.
