### ISSUE TITLE
Add support for `serialize_with` and `deserialize_with`

### ISSUE THREAD

**Issue by banool** [poem-web/poem#322]
Hey, imagine I have code like this:
```
struct MyThing {
    my_other_thing: MyOtherThing
}

struct MyOtherThing {
    bytes: HexEncodedBytes,
}

struct HexEncodedBytes(Vec<u8>);
```

As it is now, you can't impl `NewType` on `HexEncodedBytes` as it doesn't impl `ToHeader`. That's not important though, imagine I want to make my API return `HexEncodedBytes` as a string like `0x32434`. To get around this, I have to make 2 new structs: `MyThingWrapper`, `MyOtherThingWrapper`, and then a new newtype that for example encodes the `Vec<u8>` in some other way (a string, b64, etc). On top of that, I have to `impl From<MyThingWrapper> for MyThing` and all of the other types too.

As you can see, this ends up being a lot of additional wrapping code. Instead, what I'd like to do this this:

```
struct MyThing {
    my_other_thing: MyOtherThing
}

struct MyOtherThing {
    #[oai(serialize_with = "my_serializer", deserialize_with = "my_deserializer")]
    bytes: HexEncodedBytes,
}

struct HexEncodedBytes(Vec<u8>);

fn my_serializer(value: Vec<u8>) -> String {
    // convert
}

fn my_deserializer(value: String) -> Vec<u8> {
    // convert
}
```

Either that, or just pass in a serializer. With this, the spec should say that this field is a `String`, not a `Vec<u8>`.

Is there some way we could add this feature?

Thanks!

**Comment by banool** [comment]
I'm going to close this for now, I don't think this is a well-thought-out suggestion as it is.

**Comment by BatmanAoD** [comment]
For future readers, `serialize_with` and `deserialize_with` were added in #749.
