### ISSUE TITLE
[poem-openapi] `Attachment` type doesn't reflect the `Content-Disposition` header in OpenAPI spec

### ISSUE THREAD

**Issue by DDtKey** [poem-web/poem#325]
## Expected Behavior
I want to see `Content-Disposition` in `OpenAPI` spec when I'm using `poem_openapi::payload::attachment::Attachment`

I had to add `response_header` manually:

![image](https://user-images.githubusercontent.com/26835520/179821766-e59bca61-a512-43fa-9a2b-00c2fde6180a.png)

## Actual Behavior
There is no header in OpenAPI spec

## Steps to Reproduce the Problem

1. create endpoint with response type(`impl ApiResponse`) and include Attachment 
2. Take a look at OpenAPI spec

## Specifications

- Version: 2.0.3

**Comment by sunli829** [comment]
You should add headers like this so they can be in the OpenAPI spec.

https://github.com/poem-web/poem/blob/1ad98109e8e76e5aa78ad1863844ffe02512aefa/poem-openapi/tests/response.rs#L105

**Comment by DDtKey** [comment]
@sunli829 any comments? It looks like a bug to me

**Comment by sunli829** [comment]
You can define the response like below.

```rust
    #[derive(ApiResponse)]
    enum MyResponse {
        #[oai(status = 200)]
        Ok(
            Attachment<Vec<u8>>,
            #[oai(header = "Content-Disposition")] String,
        ),
    }
```

**Comment by DDtKey** [comment]
@sunli829 well, I described it above: `Attachment` already fill this header, so it conflicts with type - in this case I'll override the value of the header.. And moreover I have to fill it manually every-time

**Comment by sunli829** [comment]
I would create a `Content-Disposition` header in the schema for `Attachment`, but this require some changes to the `Payload` trait.

**Comment by DDtKey** [comment]
It's not urgent for me, I have workaround with `response_header` on endpoint. 
But I think this feature makes sense. Such types should be self-declared 🙂 It will allow to create response types with embedded headers, seems to be cool.

I really appreciate your help and such great maintenance for `poem` 🚀

**Comment by DDtKey** [comment]
Looks like it's done 🚀 

Thanks!

**Comment by itsbalamurali** [comment]
@DDtKey can you please close this issue?

**Comment by glebpom** [comment]
`AttachmentType` is not exposed publicly: https://github.com/poem-web/poem/issues/344

**Comment by DDtKey** [comment]
Another related issue:
- p**revious behavior**: type was hardcoded to `attachment`
- **current behavior:** default type `inline`

It breaks backward capability  🤔  Not sure if it should be fixed, cause it's already released

**Comment by glebpom** [comment]
It could be fixed by yanking the current version
