### ISSUE TITLE
UI on custom paths?

### ISSUE THREAD

**Issue by andrewthetechie** [poem-web/poem#334]
Is it possible to run the swagger-ui, redoc, or rapidoc on a custom path?

**Comment by chunghha** [comment]
You may want to do like this.

<img width="1147" alt="Screen Shot 2022-07-24 at 12 50 27 AM" src="https://user-images.githubusercontent.com/24458075/180634307-ebcb9ad5-cd20-402c-a415-cd16412d20ee.png">

**Comment by andrewthetechie** [comment]
Ty @chunghha! I'll give that a try

**Comment by andrewthetechie** [comment]
Confirming this is working for me. Might be a good example or documentation point.

If I get some spare time, I'll PR an example up later
