### ISSUE TITLE
OpenTelemetryMetrics should record matched route pattern only, rather than raw path

### ISSUE THREAD

**Issue by DCjanus** [poem-web/poem#337]
For now, [OpenTelemetryMetrics](https://docs.rs/poem/1.3.35/poem/middleware/struct.OpenTelemetryMetrics.html) record request uri as metric label, which may cause serious problem, like OOM, in those case

1. random path scan
2. param in paths, like `/users/:id`

Which means, we should record matched route pattern only, in above cases, prometheus should record label `/users/:id` only, and ignore `NotFound` responses,

**Comment by DCjanus** [comment]
Unfortunately, for now,  structure of `Route` may hard to impl this feature, I'm not sure how to resolve this issue.

**Comment by sunli829** [comment]
It's a very good proposal, and it's totally achievable, I'll add it later.

**Comment by Christoph-AK** [comment]
I think this is still worth implementing.

**Comment by DCjanus** [comment]
To achieve this goal, we have to re-design Route module, is there anyone would like to handle this, or post some web-framework-route module design to help us.

**Comment by sunli829** [comment]
I'll start working on this later.

**Comment by sunli829** [comment]
I added  a `path_pattern` label to `OpenTelemetryMetrics` middleware in `master` branch, please help me test it.

**Comment by DCjanus** [comment]
is there any exmaple for path_pattern？I'm not sure how to use it

**Comment by sunli829** [comment]
You don't need to do anything, I've added the `http.path_pattern` label to the logs in the `OpenTelemetryMetrics` middleware.

https://github.com/poem-web/poem/blob/a7803d77e6cf39c9d6fcefb4377318871780b65f/poem/src/middleware/opentelemetry_metrics.rs#L80
