### ISSUE TITLE
How come `ToJSON` and `ParseFromJSON` exist?

### ISSUE THREAD

**Issue by banool** [poem-web/poem#350]
Hey, as I look through more of the codebase, I so far see that every implementation of `ToJSON` / `ParseFromJSON` just calls out to serde directly. I wonder why these traits exist, couldn't we just use `Serialize` and `Deserialize`?

**Comment by Christoph-AK** [comment]
In a similar sense, is serde the best candidate for json serialisation here? Are there maybe better performing/smaller/lighter crates to use for JSON?

**Comment by sunli829** [comment]
Not using `serde` to parse and serialize json.

**Comment by ChillFish8** [comment]
As a note to this, we use it when mirroring and transforming internal API responses.

The separation lets us use the same model but with different serialization/deserialization behaviours between them. (Mostly with renaming)
