### ISSUE TITLE
How to access `operation_id` in middleware?

### ISSUE THREAD

**Issue by banool** [poem-web/poem#351]
Hey, I have some logging middleware where I'd love to do log based on `operation_id`, but I don't know how I can access that data from middleware. I can't see anything on `request` or `next` that lets me access this information about the endpoint.

Thanks!

**Comment by sunli829** [comment]
I'll add it tomorrow.

**Comment by sunli829** [comment]
When I thought about it, I found that this is not easy to achieve, the outer middleware cannot get the `operation_id`. 😂

**Comment by banool** [comment]
I see, I wonder if there is some way I can pass it in manually per route then into some middleware? Or get the function name of the handler instead?

Currently I'm using the path but that is a breaking change compared to our previous warp based method.

**Comment by sunli829** [comment]
I've add an example to show how to get the `operation-id` from the response.

https://github.com/poem-web/poem/tree/master/examples/openapi/log-with-operation-id

**Comment by banool** [comment]
omg you're such a legend, thanks so much for this, looks like it'll work great. I'll try it out soon, probably on the next poem-openapi release to crates.io

**Comment by banool** [comment]
Used it here: https://github.com/aptos-labs/aptos-core/pull/2781! Still testing but looks good!
