### ISSUE TITLE
Poem release cadence

### ISSUE THREAD

**Issue by banool** [poem-web/poem#358]
Hey, there are a handful of changes in main that I'd like to use, but currently they're not in a released on crates.io. This means I have to target the git repo instead.

As I understand it now, releases are just done by hand (since you have to update the changelog and all that). However maybe we could find a way to do the change logs automatically, eg from a part of the commit message, so we have some maximum time between when a change lands and when it gets released?

**Comment by sunli829** [comment]
Yes, I do it by hand. 😂
