### ISSUE TITLE
Allow paths to be excluded when using ForceHTTPS

### ISSUE THREAD

**Issue by andrewthetechie** [poem-web/poem#360]
## Description of the feature
I use the ForceHTTPS middleware to redirect requests to HTTPS for my app. Unfortunately, this causes problems when deploying in k8s with health checks.

I'd like to be able to exclude a path from ForceHTTPS

**Comment by sunli829** [comment]
I added a `filter` method, which should solve the problem.

**Comment by andrewthetechie** [comment]
Very cool! Thanks :)
