### ISSUE TITLE
Poem converts cases differently than serde

### ISSUE THREAD

**Issue by banool** [poem-web/poem#362]
Code demonstrating the issue:
```
use serde::{Deserialize, Serialize};
use poem_openapi::{Object, Union};
use poem_openapi::types::ToJSON;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Object)]
pub struct Ed25519Signature {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Object)]
pub struct MultiEd25519Signature {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Object)]
pub struct MultiAgentSignature {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Union)]
#[serde(tag = "type", rename_all = "snake_case")]
#[oai(one_of, discriminator_name = "type", rename_all = "snake_case")]
pub enum TransactionSignature {
    Ed25519Signature(Ed25519Signature),
    MultiEd25519Signature(MultiEd25519Signature),
    MultiAgentSignature(MultiAgentSignature),
}

fn main() {
    let test = TransactionSignature::Ed25519Signature(Ed25519Signature{});
    println!("test: {}", serde_json::to_string(&test).unwrap());
    println!("test: {}", test.to_json().unwrap());
}
```

Output:
```
test: {"type":"ed25519_signature"}
test: {"type":"ed_25519_signature"}
```

I feel we should strive to make the behavior match here.

**Comment by banool** [comment]
Upon diving deeper, I see Poem uses inflector while serde uses its own thing: https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs.

**Comment by banool** [comment]
I don't think I have the context necessary to make a change here, do you have any ideas @sunli829? I figure the best way would be to leverage serde more directly (perhaps optionally, only if the user wants) instead of implementing `rename_all` separately. This would enable https://github.com/poem-web/poem/issues/329 too.

**Comment by banool** [comment]
Anything will help, I'll make the fix myself, I need a solution to this soon, it's blocking a critical rollout.

**Comment by banool** [comment]
Seems like the serde stuff is accessible: https://crates.io/crates/serde_derive_internals. I might try make a PR.

**Comment by sunli829** [comment]
Can't use `serde` directly, because can't fully support the `serde` annotation, I currently use the `Inflector` crate for case conversion, I will try another one.

**Comment by banool** [comment]
Perhaps relying on serde_derive_internals might be the best option? Let me know if you're working on this, if not I can try implement it myself :)

**Comment by sunli829** [comment]
I'm working on this.

**Comment by sunli829** [comment]
I've push changes in `master` branch, pls help test it.

**Comment by banool** [comment]
Works perfectly, thanks a lot! Using it in https://github.com/aptos-labs/aptos-core/pull/2764 to great effect.
