### ISSUE TITLE
OpenAPI - Single Query Param Key With Multiple Value

### ISSUE THREAD

**Issue by crc-sstubbs** [poem-web/poem#367]
Hi,

Firstly thank you for this amazing project. It works really well and makes performant OpenAPI possible which is awesome. I'm trying to implement sorting. Something along the lines of https://specs.openstack.org/openstack/api-wg/guidelines/pagination_filter_sort.html#sorting

Using `param::Query<Vec<String>>` does allow multiple values through swagger ui however they conflict by creating a key for each value as explode is set to true by default and I only get access to the last entry of this vec. How would I set explode to false? https://stackoverflow.com/questions/62527254/how-does-open-api-3-0-support-a-single-query-param-key-with-multiple-values

I can set the query param as a string and manually split the comma separated value entered but would rather it is properly documented in swagger ui as an array.

**Comment by sunli829** [comment]
This is not supported yet, I will add it later.

**Comment by crc-sstubbs** [comment]
OK thanks will use a string for now then and update it when it's added.

**Comment by banool** [comment]
Adding this feature would probably also make this easier: https://github.com/poem-web/poem/issues/342

**Comment by sunli829** [comment]
Released in `v2.0.9`

https://github.com/poem-web/poem/blob/dbe761a87d79f32fc7d59418c1aa1106cd1791e1/poem-openapi/tests/operation_param.rs#L106

**Comment by crc-sstubbs** [comment]
Wow that was quick. Tested it out. Works perfectly. This project never ceases to amaze me. Thank you very much!

**Comment by mathiversen** [comment]
I tried to copy paste this but i get the following error when i run it locally:
`curl "http://localhost:3000?v=1,2,3" => invalid type: sequence, expected i32`
Not sure what I'm doing wrong? :thinking: 

Would this support Uuid as well?
