### ISSUE TITLE
Why doesn't openapi Path url decode?

### ISSUE THREAD

**Issue by stdlout** [poem-web/poem#375]
Hi,

I've tried to use poem_openapi::param::Path\<Email\>, but I get bad request because the segment is url encoded.  Testing with Path\<String\> I can see that indeed the String is not decoded.  This seems counter-intuitive to me, is there perhaps another type to use to ensure the decoding is done?

Thanks!

**Comment by sunli829** [comment]
I have fixed this issue on `master` branch, could you please help to test it? 🙂

**Comment by stdlout** [comment]
Awesome, I will as soon as I get a chance - it's not part of my day job, unfortunately.

Thanks for the quick fix!
