### ISSUE TITLE
Route redirect with poem-openapi

### ISSUE THREAD

**Issue by banool** [poem-web/poem#376]
Hey, imagine I have an API defined with the `#[derive(Openapi)]` macro invocation, and in that API I've got something at the path of `/hello`. If I wanted an alias for the same path at `/hey` is there a way to do that? I don't want the alias to appear in the generated spec. Should I just add a new route handler for `/hey` and add the thing to ignore it from the generated spec? Thanks!

**Comment by sunli829** [comment]
What do you think if I add a `hidden` attribute?

```rust

#[OpenApi]
impl MyApi {
    #[oai(path = "/hello", method = "get")]
    fn hello() { }

    #[oai(path = "/hello", method = "get", hidden)]  // hidden attribute to hidden this api in the document
    fn hey() { }
}

```

**Comment by banool** [comment]
I think that'd work pretty well, sounds good to me! Either that or something like this:
```
#[OpenApi]
impl MyApi {
    #[oai(path = "/hello", method = "get", aliases = ["/hey", "/hi"])]
    fn hello() { }
}
```

**Comment by banool** [comment]
Closing this since `hidden` works for this :)
