### ISSUE TITLE
Documentation of API behind Proxy

### ISSUE THREAD

**Issue by hffmnn** [poem-web/poem#377]
Hi,

I'd like to document an API that is behind a Proxy. This Proxy adds some path, e.g. `v1`. So the path to an endpoint would be `<some_url>/v1/todos`. Is it possible to document that with poem somehow? As soon as I add something like `#[oai(path = "/v1/todos", method = "get")]` the documentation would be correct, but the Endpoint would be reachable under `/v1/v1/todos`.

Another example case would be e.g. an AWS Lambda behind an AWS API Gateway: The API Gateway sets the route, and the lambda would get mounted to `/`. But I'd like to document the full path to the API Endpoint somehow

```
API GW               -> Lambda Mount point -> OpenAPI
/get_todos          -> /                   -> /get_todos
```

Somehow, I'd need an option to distinguish between a mount path and the path to document. Does that make sense?

**Comment by sunli829** [comment]
> I'd like to document an API that is behind a Proxy. This Proxy adds some path, e.g. v1. So the path to an endpoint would be <some_url>/v1/todos. Is it possible to document that with poem somehow? As soon as I add something like #[oai(path = "/v1/todos", method = "get")] the documentation would be correct, but the Endpoint would be reachable under /v1/v1/todos.

I think mounting this endpoint to `/v1` should work.

```rust
let app = Route::new().nest("/v1", 
    OpenApiService::new(..).server("<some_url>/v1") // specify the server to ensure that these apis can be called correctly in the swagger ui.
);
```

**Comment by hffmnn** [comment]
Ah, ok. So the `server` part is pure annotation and has nothing to do with the actual mounting. In my case I'd add something like this:

```
let app = Route::new().at("/", 
    OpenApiService::new(..).server("<some_url>/v1") // specify the server to ensure that these apis can be called correctly in the swagger ui.
);
```

Thanks a lot!
