### ISSUE TITLE
Setting an event type with poem_openapi::payload::EventStream?

### ISSUE THREAD

**Issue by bryanlarsen** [poem-web/poem#378]
poem::web::sse::Event gives a mechanism (`event_type()`) for adding an event type to an sse event.

poem_openapi::payload::EventStream does not, at least as far as I can tell.   Is this possible?

**Comment by sunli829** [comment]
Here is the example to show how to convert the message to event:

https://github.com/poem-web/poem/blob/91614e4a608dcde121b941f1618e3c1ce16046b5/poem-openapi/src/payload/event_stream.rs#L70

**Comment by bryanlarsen** [comment]
Awesome!   2.0.11 isn't on cargo yet, so I switched to git to try it out.

I was working from your poem_openapi sse example, so I ended up with something like this:

```
    #[oai(path = "/foo", method = "get")]
    async fn foo(&self) -> EventStream<BoxStream<'static, serde_json::Value>> {
        EventStream::new(
            async_stream::stream! {
                for i in 0.. {
                    tokio::time::sleep(Duration::from_secs(1)).await;
                    yield serde_json::json!({"a": 3, "b": i});
                }
            }
            .boxed(),
        )
        .to_event(|ev| Event::message(ev.to_string()).event_type("foo"))
    }
```

Feel free to put this example into your repo.
