### ISSUE TITLE
Parsing a Path parameter with a trailing extension

### ISSUE THREAD

**Issue by sunli829** [poem-web/poem#381]
### Discussed in https://github.com/poem-web/poem/discussions/380

<div type='discussions-op-text'>

<sup>Originally posted by **phaer** September  2, 2022</sup>
Hello,

I am trying to use a Route like `"/notebooks/:id.pdf` but, it seems that poetry interprets this as a parameter called "id.pdf" instead of an parameter "id", followed by the string ".pdf". Using a regex like `/notebooks/:id<[^\\.]>.pdf` does not work as expected either. 

Swagger UI confirms that the parameters aren't interpreted as expected: 
![image](https://user-images.githubusercontent.com/101753/187967937-f80a65f5-9676-44a6-9e49-cd62fd1f8046.png)

Is this something supported by poem? Am I missing something? </div>

**Comment by sunli829** [comment]
I reviewed the code, this is not a bug, the current matching algorithm cannot support extensions.

I need to think about how to do it. 😀

**Comment by sunli829** [comment]
I thought about it and suggested the following solution:

```rust
#[oai(path = `/notebooks/:id`)]
async fn handler(id: Path<String>) -> Result<()> {
    if id.ends_with(".svg") {
        // do something
    } else {
        Err(Error::from_status(StatusCode::NotFound))
    }
}
```

**Comment by phaer** [comment]
Thanks for the quick response! But its more a work-around than a solution in my opinion as, ideally, I'd like to have three different handlers: "/notebooks/:id", "/notebooks/:id.pdf" and "/notebooks/:id.png". With this work-around one has to cram all 3 of them into a single handler and do the rest of the matching myself.
