### ISSUE TITLE
[swagger ui] How to support multiple authentications for different routes

### ISSUE THREAD

**Issue by taodongl-citrix** [poem-web/poem#382]
## Description of the feature
My server provide multiple services: github webhook and user dashboard, so there are different authentication.
Could the same swagger UI support multiple authentications for different routes?

## Code example (if possible)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/67308160/189071449-4af22d73-ce95-4e4a-af0b-da19bace6771.png">

**Comment by sunli829** [comment]
It doesn't seem possible, multiple authentications not defined in the OpenAPI specification.

**Comment by taodongl-citrix** [comment]
Okay, I will create muitiple swagger-ui in server.
