### ISSUE TITLE
swagger ui submit get error: URL scheme must be "http" or "https" for CORS request.

### ISSUE THREAD

**Issue by bingryan** [poem-web/poem#391]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/41174435/190923463-a3bdab74-c1d2-4d52-9d18-aed297bfcc5b.png">

**Comment by sunli829** [comment]
Swagger UI provides several possible reasons, so check the real reason why `http://localhost:3000/api/hello` returns an error.
