### ISSUE TITLE
EmbeddedFilesEndpoint strip prefix

### ISSUE THREAD

**Issue by andrewbaxter** [poem-web/poem#396]
## Description of the feature

Allow specifying a prefix to be trimmed from url paths before resolving embedded files.

For instance, right now a request to
```
/assets/abc.jpg
```
will result in an embedded file lookup of
```
assets/abc.jpg
```
If the embedded files are all at the root you may want the look up to go to
```
abc.jpg
```
instead.

This would be useful if hosting multiple sets of static files that need to be located somewhere other than at the `/` route, or if the assets are at a non `/` route to avoid ambiguous or clashing paths.

## Code example (if possible)

Maybe something like
```
EmbeddedFilesEndpoint::<STATIC>::new().with_prefix("/assets")
```

**Comment by andrewbaxter** [comment]
Actually it would be nice if rather than specifying a prefix like `"/assets"` it could be taken from the route suffix like 
```
.at("/assets/*tree", get(EmbeddedFilesEndpoint::<STATIC>::new()))
```
(taking the `*tree` part of the path)

**Comment by sunli829** [comment]
I think you should use `nest`.

```rust
route.nest("/assets", EmbeddedFilesEndpoint::<STATIC>::new())
```

**Comment by andrewbaxter** [comment]
Ah, I see! You're right, I didn't think of that but it seems obvious in retrospect.  Thank you!
