### ISSUE TITLE
Impl `Example` trait for `NewType` in poem-openapi

### ISSUE THREAD

**Issue by ZodiacWind** [poem-web/poem#404]
## Description of the feature

I would like to use NewType such as 

```
#[derive(NewType)]
pub struct MyString(String)
```

And I also want to generate example for it in my OpenAPI docs, is it possible to do that?

## Code example (if possible)

```
#[derive(NewType)]
#[oai(exmpale)]
pub struct MyString(String)

impl Example for MyString {

    fn example() -> Self {
        Self("abc".to_string())
    }
}

```

**Comment by sunli829** [comment]
Added in `master` branch 🙂

**Comment by ZodiacWind** [comment]
Thanks, good job!
