### ISSUE TITLE
deny_unknown_fields doesn't work with flatten

### ISSUE THREAD

**Issue by stepantubanov** [poem-web/poem#411]
Getting `unknown field` error with a flattened `Object`.

```rust
// poem-openapi/tests/object.rs
#[test]
fn deny_unknown_fields_flatten() {
    #[derive(Object, Debug, PartialEq, Eq)]
    #[oai(deny_unknown_fields)]
    pub struct ApiDocumentCreateItem {
        #[oai(flatten)]
        field: ApiFieldName,
        value: String,
    }

    #[derive(Debug, Object, PartialEq, Eq)]
    #[oai(rename_all = "snake_case")]
    pub struct ApiFieldName {
        pub field_name: String,
    }

    assert_eq!(
        ApiDocumentCreateItem::parse_from_json(Some(json!({
            "field_name": "a",
            "value": "v",
        })))
        .unwrap(),
        ApiDocumentCreateItem {
            field: ApiFieldName {
                field_name: "a".into()
            },
            value: "v".into(),
        }
    );
}

```

## Expected Behavior

Object parsed correctly.

## Actual Behavior

Error: ``failed to parse "ApiDocumentCreateItem": unknown field `field_name`.``

## Steps to Reproduce the Problem

1. Add reproduce fn to poem-openapi/tests/object.rs.
2. Run `cargo test --package poem-openapi --test object`
3. See test failure.

## Specifications

Latest master branch.

**Comment by sunli829** [comment]
flatten attribute is not supported in combination with structs that use deny_unknown_fields.

**Comment by sunli829** [comment]
I added an error message.

**Comment by stepantubanov** [comment]
@sunli829 Oh, right, makes sense. Thanks for adding a message! 👍
