### ISSUE TITLE
Exclude fields of struct for response

### ISSUE THREAD

**Issue by chikko80** [poem-web/poem#426]
Its probably another dumb question but maybe someone else in the future will also have this question so I thought it's worth asking here.

Is there an easy way to exclude some fields of a struct in a response?
For example, I don't want to send out the password and salt for my user struct. I tried to skip with serde but didn't have any success.
I have absolutely no idea how to do it right now - probably there is some poem-specific mechanism that i am missing.

At the moment - on my getter endpoint - i send out the user struct which derives Object from poem_openapi
Thanks for any help!

**Comment by chikko80** [comment]
Works like a charm!
Is there any list of all the features #[oai] provides?
I've already checked the docs but couldn't find anything about skip that was the reason why i asked

**Comment by sunli829** [comment]
https://docs.rs/poem-openapi/2.0.19/poem_openapi/derive.Object.html

**Comment by chikko80** [comment]
Oh perfect, i need to check all the docs in-depth
