### ISSUE TITLE
openapi: Path parameter is not shown in parameters

### ISSUE THREAD

**Issue by fxdave** [poem-web/poem#451]
## Expected Behavior
https://swagger.io/docs/specification/describing-parameters/

## Actual Behavior
![image](https://user-images.githubusercontent.com/12275699/208196854-c294eed9-85c2-4f07-b468-75eb4307a3b9.png)

## Steps to Reproduce the Problem
```rust
#[oai(path = "/warehouse/:id", method = "put")]
    pub async fn put(
        &self,
        id: Path<String>,
        data: Json<WarehouseEntry>,
        _auth: BearerAuthorization,
        db: Data<&WarehouseRepository>,
    ) -> Result<Json<CreateSuccessResponse>> {
        let entry_inserted = db.clone().update(&id, data.0).map_err(GenericError::from)?;
        Ok(Json(CreateSuccessResponse { entry_inserted }))
    }
```

## Specifications

- Version: 1.3.50
- Platform: linux

**Comment by sunli829** [comment]
You should use `poem_openapi::param::Path` instead of `poem::web::Path`.

**Comment by fxdave** [comment]
You are right. Thanks, Sorry for the bug report.
