### ISSUE TITLE
Provide optional URL prefix to generated spec json

### ISSUE THREAD

**Issue by VersBinarii** [poem-web/poem#470]
## Description of the feature
Would you consider adding an option to pass in url prefix into the generated spec?
```
"paths" : {
    "/my_prefix/rest/of/my/path" : {
      "get" : {
        "parameters" : [
          {
            "name" : "X-Customheader",
            "in" : "header",
            "required" : true,
            "schema" : {
              "type" : "string"
             }
           }
         ]
      }
    ... snip ...
 
```

## Code example (if possible)
Maybe something like that:

```
let spec_options = SpecOptions::default().with_url_prefix("/my_prefix");
let my_api_schema = my_api.spec_endpoint_with_options(options);
```

**Comment by sunli829** [comment]
Maybe it can be solved with `prefix_path` attribute.

https://github.com/poem-web/poem/blob/7ada5b69c94c0a98ddff64172703ed61c3386fdf/poem-openapi/tests/api.rs#L88

**Comment by VersBinarii** [comment]
Unfortunately not. This prefix comes from config file and additionally we have abstraction over the handlers so the prefix is dynamic.

**Comment by sunli829** [comment]
Welcome to PR😁
