### ISSUE TITLE
Derive Types only apply to crate in which they were derived

### ISSUE THREAD

**Issue by FallingSnow** [poem-web/poem#472]
I am having trouble with using my `TTest` struct to deserialize the body of a request.

If I place the following code in my main crate it works correctly.
```rust
use poem_openapi::{Object};
use serde::{Deserialize, Serialize};
#[derive(Object, Serialize, Deserialize)]
pub struct TTest {
    ok: bool
}
```

However when I move this code to another "common" crate, I end up with an error that `ToJSON` and `ParseFromJSON` are not implemented.
```rust
error[E0277]: the trait bound `common::TTest: ToJSON` is not satisfied
  --> speexdp/src/web/mod.rs:69:15
   |
69 |         body: Request<TTest>,
   |               ^^^^^^^^^^^^^^ the trait `ToJSON` is not implemented for `common::TTest`
   |
   = help: the following other types implement trait `ToJSON`:
             &'a str
             &T
             &[T]
             Arc<T>
             BTreeMap<K, V>
             BTreeSet<T>
             Box<T>
             HashSet<T>
           and 35 others
note: required by a bound in `api::Request`
  --> speexdp/src/web/api.rs:49:45
   |
47 | pub enum Request<T>
   |          ------- required by a bound in this
48 | where
49 |     T: ParseFromJSON + Send + Sync + Type + ToJSON + for<'b> Deserialize<'b>,
   |                                             ^^^^^^ required by this bound in `api::Request`
```

If I try to manually implement `ToJSON` for I get a conflicting implementation error because it is already implemented from the derived Object type.

It seems that the derived `ToJSON` implementation only exists in the crate is was derived in...

**Comment by sunli829** [comment]
This is weird, are you sure both your crates depend on the same version of `poem-openapi`?

**Comment by FallingSnow** [comment]
Amazing, that was it. You're amazing, thank you!

Jeez I wish I had known that after spending a few hours yesterday trying to figure this out.
One crate was pointed to git the other to crates.io. Interestingly both has the same version attribute.

I've seen where errors tell you you have 2 different versions, don't know why I didn't get that this time.
