### ISSUE TITLE
ApiResponse in tracing middleware

### ISSUE THREAD

**Issue by dreamerlzl** [poem-web/poem#475]
# Problem
Due to the current implementation of `poem::error::from_response` (blanket impl of `From<T: ApiResponse> for poem::Error`)

https://github.com/poem-web/poem/blob/2d91d10a1f23ef4553e33c7981be7e78f0cd969b/poem/src/error.rs#L313

the error section of the output in the `Tracing` middleware is always `response`

https://github.com/poem-web/poem/blob/2d91d10a1f23ef4553e33c7981be7e78f0cd969b/poem/src/error.rs#L211

there would be conflicts if I try to do this (conflicting with `#[derive(ApiResponse)]`)
```rust
impl From<ApiErrorResponse> for poem::Error {
    fn from(value: ApiErrorResponse) -> Self {
        match value {
            ApiErrorResponse::BadRequest(e) => {
                poem::Error::new(e.as_str().into(), poem::http::StatusCode::BAD_REQUEST)
            }
            _ => poem::Error::from_response(value),
        }
    }
}
```

# Example & Code
output example:
```
{"v":0,"name":"zero2prod","msg":"[REQUEST - EVENT] error","level":30,"hostname":"wright","pid":57270,"time":"2023-01-06T08:03:41.984148073Z","target":"poem::middleware::tracing_mw","line":69,"file":"/home/wright/.cargo/registry/src/github.com-1ecc6299db9ec823/poem-1.3.48/src/middleware/tracing_mw.rs","duration":"237.212µs","status":"400 Bad Request","error":"response","uri":"/","version":"HTTP/1.1","method":"POST","remote_addr":"unknown://unknown"}
```

my code is here

https://github.com/dreamerlzl/zero2prod/blob/test/src/routes/subscriptions.rs#L202

# Question
Is it possible to use `E: ApiResponse` in `Result<T, E>` while allowing custom `error` display in tracing? In my code example, I also want to trace the content inside `BadRequest(PlainText<String>)`

**Comment by sunli829** [comment]
I'm adding descriptions to errors generated by `ApiResonse`.

**Comment by dreamerlzl** [comment]
Thank you! I believe this example demonstrate how to customize error display in tracing.

https://github.com/poem-web/poem/blob/master/poem-openapi/tests/response.rs#L467
