### ISSUE TITLE
Why is PathPattern not publicly available?

### ISSUE THREAD

**Issue by arkadiuszbielewicz** [poem-web/poem#529]
Hi, I would like to ask, whether there is any reason why `PathPattern` is not publicly available? 
Due to some incompatibilities with [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md ) I would like to write my own `OpenTelemetryMetricsEndpoint` layer. But due to not being able to access `resp.data::<PathPattern>()` I miss most important data.

**Comment by sunli829** [comment]
This should be a bug , it should be public. 🙂

**Comment by arkadiuszbielewicz** [comment]
Solved by [#522 ](https://github.com/poem-web/poem/pull/522)
