### ISSUE TITLE
How to extention auth for admin role and orther user roles?

### ISSUE THREAD

**Issue by xxf2103625** [poem-web/poem#562]
I use the middleware to check request head token in poem-openapi.
I can resove the Claims key for user role e.g. in middleware,
but where to define the role "admin"  just allow admin users to vist the api "/api/admin/adduser" e.g.
I gess I can define it in #Openapi
```rust
#[oai(path = "/userlist", method = "get", auth_role = "admin")]
``` 
Or better in 
```rust
#[OpenApi(auth_role="admin")]
``` 
But I dot know how to extend this and how can I get "admin" in middleware.

**Comment by danechitoaie** [comment]
@xxf2103625 how do you handled this?
