### ISSUE TITLE
serialize and display a structure as a primitive type (String)

### ISSUE THREAD

**Issue by rxdiscovery** [poem-web/poem#587]
Hello,
First of all, I'd like to thank you for your hard work. It's really the only web framework available in the Rust universe that integrates the OpenAPI documentation natively.

i'm migrating a project from actix-web to poem, and i'm stuck on one part.
I have a structure that contains two member values, but I'd like to serialize it as a String and display it as a String on the Doc (swagger) too.

```rust
#[derive(Serialize, Deserialize, Default, Clone, Debug)]
struct ID {
     salt : String,
     value : String,
}


#[derive(Object,Serialize, Deserialize, Default, Clone, Debug)]
struct TestDTO {

    #[serde(rename = "id")]
    #[oai(rename = "id")]
    id : ID,


    #[serde(rename = "name")]
    #[oai(rename = "name")]
    name : String,
}

```
I want it to generate this :

```json
 "TestDTO": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "string"   <------------------------------
          },
         "name": {
            "type": "string"
          },

```

I want to force the value of "type" to "string",  and how to define your own way of serializing and deserializing the object? (before I used serde "serialize_with" )

( for example, on the utoipa crate, there's a macro that allows you to force the type of a field:  ` #[schema(value_type = String)]` )

I tried to implement ToJSON trait, but the compiler tells me it's already implemented ( "Object" derive )

I've also tried to use the example (openapi/custom-payload), but it's not at all comprehensible to me. 

if you can give me a code that shows how to do it, I'd be extremely grateful.

I'm really blocked on this part, thanks in advance for your help.

**Comment by rxdiscovery** [comment]
Hello again,
I took inspiration from the code here:

https://github.com/poem-web/poem/blob/master/poem-openapi/src/types/external/string.rs

and it works well, can you confirm if this is the right technique to follow or is there something simpler?

**Comment by sunli829** [comment]
- Yes, you should implement `Type` trait for `ID`.

- `#[oai(rename = "id")]` is unnecessary, unless you want to change the name.

**Comment by rxdiscovery** [comment]
what I meant by my question is that "aoi" replaces "serde", is the use of serde macros useless with "poem/open-api" ? 

#[serde(rename = "id")]  VS  #[serde(rename = "id")]

**Comment by sunli829** [comment]
To avoid confusion, poem-openapi does not support parsing serde attributes. 🙂

**Comment by rxdiscovery** [comment]
thank you very much, that answers my question :+1:
