### ISSUE TITLE
Can I use poem with Include_dir or something similar

### ISSUE THREAD

**Issue by Alfiec7113** [poem-web/poem#601]
Is it possible to use something like include_dir to include a static website for me to host built into the binary?

use include_dir::{include_dir, Dir};
static PROJECT_DIR: Dir<'_> = include_dir!("out");

    let app = Route::new()
    .nest(
        "/",
        StaticFilesEndpoint::new(PROJECT_DIR.path())
            .show_files_listing()
            .index_file("index.html"),
    )
    
    this doesn't seem to work.

**Comment by sunli829** [comment]
An example

https://github.com/poem-web/poem/tree/master/examples/poem/embed-files

**Comment by Alfiec7113** [comment]
Thanks Sunli!
