### ISSUE TITLE
How can I respond early in the middleware to avoid executing `ep.call()`?

### ISSUE THREAD

**Issue by BinChengZhao** [poem-web/poem#61]
I recently ran into some tricky issues migrating my project from `actix-web` to `poem`.

Problem description.

In `actix-web` middlerware, I can split the task into two steps.

1. status determination success -> service.call() (similar to ep.call() in `poem`)
2. status determination failure, early response -> via req.error_response() (ServiceRequest::error_response)

Step 1 can be implemented in poem, but no good solution has been found for step 2.

Referring to the middleware implementation in example,  can use extensions to add a `statusX`
handler with extractor to extract `Result<Data<StateX>>` to handle it by itself,

But I have 50/60 handlers and it is not convenient to add a state to each handler.
And every time I add middleware, I need to add `State*` to the handler, which will make the handler very long. 

I would like to ask you for some advice.

**Comment by BinChengZhao** [comment]
> Is this example helpful? https://github.com/poem-web/poem/blob/master/examples/poem/handling-404/src/main.rs

Thank you, but this is not what I wanted ~

**Comment by RustChater** [comment]
always one option fit for you:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94d5bdc3bf0a3b5eb3362c8ad5568849
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=234a74bb4f3dda0a083451ea3404edb1
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c8ac055997777d1818ed7400bc6af0be

**Comment by sunli829** [comment]
I added an example to show how to do this.

https://github.com/poem-web/poem/tree/master/examples/poem/basic-auth
