### ISSUE TITLE
Nest UI and API service at the same path?

### ISSUE THREAD

**Issue by Jawbone999** [poem-web/poem#613]
Sorry if this is simple, but I'm wondering if it is possible to create an API with the following route structure:
`/` => OpenAPI Swagger UI
`/whatever` => API business logic endpoint(s)

I have a minimal example [here](https://github.com/Jawbone999/poem_issue_minimal/blob/4c9606f1dd9d248979543614713469df72d3f86d/src/main.rs).

The behavior in the linked project is that the `/info` route works, but `/` is not found.
The desired behavior is that the two routes can co-exist, since none of the paths truly conflict.

I've tried multiple combinations of `nest`/`at`, but I can't find a way to get both services to share a root path. I don't want to prepend all my paths with `/api` or view my UI at `/ui`.

Thanks!

**Comment by sunli829** [comment]
Ugly, but works. 🙂

```rust
  let api_service = OpenApiService::new(Api, "Example API", "1.0");
    let ui = Arc::new(api_service.swagger_ui().map_to_response());

    let api_service_ep = Arc::new(api_service.into_endpoint().map_to_response());
    let handler = poem::endpoint::make(move |req| {
        let ui = ui.clone();
        let api_service_ep = api_service_ep.clone();
        async move {
            if req.uri().path() == "/" && req.method() == Method::GET {
                ui.call(req).await
            } else {
                api_service_ep.call(req).await
            }
        }
    });

    let app = Route::new().nest("/", handler);
```
