### ISSUE TITLE
[poem_openapi] How to represent unions with non data members

### ISSUE THREAD

**Issue by SaculRennorb** [poem-web/poem#614]
I have roughly the following structs that i want to serialize and send out as json:
```rs
use serde::Serialize;

#[derive(Serialize)]
pub struct Master {
  pub some_field : u32,
  #[serde(flatten)]
  pub detail : Detail,
}

#[derive(Serialize)]
#[serde(tag = "type")]
pub enum Detail {
  A(A),
  B(B),
  C,
  D(D),
  E
}

#[derive(Serialize)]
pub struct A {  pub a: u32 }
//[...] similar (more complex implementation for B and D, just different structures in general

```

using serde, this roughly serializes to
```json
{
 "some_field": 12345,
 "type": "A",
 "a": 45667
}
```
or in case of C (or E) just 
```json
{
 "some_field" : 12345,
 "type": "C"
}
```
which is exactly what i require.

If i try to add poem_openapi annotations to the `Detail` Union, it errors on the first member without data (`C`) with the message `Incorrect oneof definition`. As you might imagine that is not very helpful so a better error message would be appreciated, but moreover i would like to ask how to realize this type of structure with the existing annotations if at all possible.

**Comment by sunli829** [comment]
You should do it like this, Poem-openapi serialization is not as flexible as Serde, because its objects must conform to the OpenAPI specification.

```rust
    #[derive(Object)]
    pub struct Master {
        pub some_field: u32,
        #[oai(flatten)]
        pub detail: Detail,
    }

    #[derive(Object)]
    pub struct DetailA {
        a: String,
    }

    #[derive(Object)]
    pub struct DetailB {
        b: u32,
    }

    #[derive(Object)]
    pub struct DetailC;

    #[derive(Object)]
    pub struct DetailD {
        d: u32,
    }

    #[derive(Object)]
    pub struct DetailE;

    #[derive(Union)]
    #[oai(discriminator_name = "type")]
    pub enum Detail {
        A(DetailA),
        B(DetailB),
        C(DetailC),
        D(DetailD),
        E(DetailE),
    }
```

**Comment by SaculRennorb** [comment]
that's rough, but i feared as much. Thank you for the recommendation. 

I feel like these empty structs could just be generated in case of no data union members, but i don't have the time to look into it and i expect you to also have more pressing matters to attend to. 

closing this as the question has been answered
