### ISSUE TITLE
 Cookie middleware, can it support user-defined configuration properties?

### ISSUE THREAD

**Issue by BinChengZhao** [poem-web/poem#62]
## Description of the feature

Currently with `CookieJar`, each new `Cookie` stored requires manual configuration of security-related properties, which is flexible, but there is a lot of duplication of work being done.

 For a site, usually, the cookie security policy is kept consistent, and there are fewer scenarios where each key is configured individually.

 And currently `poem`, cookie middleware is automatically registered after the feature is turned on, so that the user lacks some control over the initialization of the attributes.

 I suggest: Cookie middleware, the user supports custom configuration at the start of the framework and can override the default loading of the cookie middleware.
 Subsequent `Cookie` default to go configured security properties, the use of light and elegant.

**Comment by sunli829** [comment]
I need to consider the design of the API, it is not enough to just add these methods to `CookieJarManager`.

**Comment by BinChengZhao** [comment]
> I need to consider the design of the API, it is not enough to just add these methods to `CookieJarManager`.

Thanks, because this is a requirement that requires a lot of internal structure adjustment, I will first use the existing way to implement the function.

**Comment by sunli829** [comment]
Added `CookieSession` middleware, released in `v1.0.5`
