### ISSUE TITLE
How to set response header in #[oai]

### ISSUE THREAD

**Issue by wl416195** [poem-web/poem#628]
I'm trying to set a response header in this, but I don't know what type of value it is

#[derive(ApiResponse)]
pub enum HttpResponse {
    #[oai(status = 200, header = "123")]
    Ok(PlainText<String>),
    #[oai(status = 200)]
    DownLoadSuccess(Attachment<Vec<u8>>),
}

**Comment by sunli829** [comment]
do it like this:

https://github.com/poem-web/poem/blob/5ed753e8a73a105ed345778efa104857a6ce2d91/poem-openapi/tests/response.rs#L123C21-L123C21

**Comment by wl416195** [comment]
> do it like this:
> 
> https://github.com/poem-web/poem/blob/5ed753e8a73a105ed345778efa104857a6ce2d91/poem-openapi/tests/response.rs#L123C21-L123C21

Thanks
