### ISSUE TITLE
How to register a custom Type

### ISSUE THREAD

**Issue by hseeberger** [poem-web/poem#640]
I have created a `SecretString` new type for `secrecy::SecretString` and want to use that in `Object`s. The compiler tells me to implement `Type`, which I did. Now Swagger shows `"password": "Unknown Type: secret-string"`. Do I have to register the new `Type` and if yes how?

**Comment by sunli829** [comment]
Like this, I'll provide a macro to simplify this later.

https://github.com/poem-web/poem/blob/master/poem-openapi/src/types/external/string.rs

**Comment by hseeberger** [comment]
Thank you, already found and copied that.
