### ISSUE TITLE
Issue about endpoint path suffix "/" 

### ISSUE THREAD

**Issue by RWDai** [poem-web/poem#645]
## Different behavior with 2.0.X and 3.0.4

same code:
``` rust
use poem::{listener::TcpListener, Route, Server};
use poem_openapi::{payload::PlainText, OpenApi, OpenApiService};

struct Api;

#[OpenApi(prefix_path = "/hello")]
impl Api {
    /// Hello world
    #[oai(path = "/", method = "get")]
    async fn index(&self) -> PlainText<&'static str> {
        PlainText("Hello World")
    }
}


#[tokio::main]
async fn main() {
    let api_service =
        OpenApiService::new(Api, "Hello World", "1.0").server("http://localhost:3000");
    let ui = api_service.swagger_ui();
    let app = Route::new().nest("/", api_service).nest("/docs", ui);

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(app)
        .await;
}
```
### In 2.0.x
You can access the `hello` endpoint through "http://127.0.0.1:3000/hello", but "http://127.0.0.1:3000/hello/" does not work
### In 3.0.4
Just the opposite is that you can access through "http://127.0.0.1:3000/hello/", and "http://127.0.0.1:3000/hello" does not work

This will make the cost of code changes too high when upgrading the version.

### question
The path parameter in the oai macro above Api.index cannot be left blank and cannot be empty. So how to remove the / from the Api.index path suffix?

## Specifications

- Version: 3.0.4
- Platform: platform independent

**Comment by sunli829** [comment]
fixed in `v3.0.5`
