### ISSUE TITLE
Adding Endpoints Should Not Take Ownership of Router

### ISSUE THREAD

**Issue by garver-the-system** [poem-web/poem#652]
## Description of the feature

Change `Router::at()` to use a mutable reference to `self` instead of taking ownership.

## Code example

The change I'm proposing is in [these lines](https://github.com/poem-web/poem/blob/master/poem/src/route/router.rs#L148C5-L165). At a basic level:

```diff
-    pub fn at<E>(self, path: impl AsRef<str>, ep: E) -> Self
+    pub fn at<E>(&mut self, path: impl AsRef<str>, ep: E) -> &mut Self
```

My reasons for proposing this are twofold. First, I want to break up the really long chains of `.at().at().at()` into different functions, and I don't want to have to repeatedly reassign the variable. That is:

```diff
fn build_router() -> Router {
    let mut router = Router::new();
-   router = add_foo_routes(router);
-   router = add_bar_routes(router);
+   add_foo_routes(&router);
+   add_bar_routes(&router);
} 
```

Second, I *think* there should be a performance improvement to passing references rather than copying structs around the stack. And if I understand it correctly, the performance improvement should increase significantly if larger apps are structured as above. (Or maybe it all gets inlined by compiler optimizations, I wouldn't know.)

I think this falls within my fairly novice skills, so I'll volunteer to put up a PR if the maintainers approve.

**Comment by sunli829** [comment]
I don't think this is necessary, even though the current implementation is slower, adding routes is only something that needs to be done at initialization time. 🙂
