### ISSUE TITLE
In the examples, listen on 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by schitcrafter** [poem-web/poem#664]
Listening from localhost (127.0.0.1) might work well for a development environment, but when deployed in a docker container the service will not be accessible from outside. Especially for people that know little about networking / docker in general, something like this can be very frustrating to debug - the container will be running, networking will be correctly setup, but every connection is refused.

**Comment by attila-lin** [comment]
Nice catch. 

PR are welcome!

**Comment by schitcrafter** [comment]
Alright, I'll make a PR - just to be sure, I didn't mention it in the original issue, listening on 0.0.0.0 means that the developer will most likely expose their poem service on the local network (in the case where it's not running in a container). Just wanted to mention that.

**Comment by attila-lin** [comment]
Yes, we may add some comments on `0.0.0.0` to notify the newbie.

**Comment by schitcrafter** [comment]
Not sure if I've forgotten anything, but this should be everything in examples/ plus README's and a couple doc comments

**Comment by attila-lin** [comment]
seems finished.

Please reopen if anything is wrong.
