### ISSUE TITLE
Getting user IP address from request.

### ISSUE THREAD

**Issue by marcellmittnacht** [poem-web/poem#692]
Hello!

I tried to search in the openapi examples, though I had no luck. Is there any way to get the IP address from a post request?

For a minimal, but not full code:

#[oai(path = "/test", method = "post")]
async fn test(&self, some_post_data: Json<SomeStruct>) -> Result<SomeResponseResult, SomeResponseError> {
    let user_ip_addr = .....
}

**Comment by djarb** [comment]
I think you're looking for https://docs.rs/poem/1.3.58/poem/web/struct.RemoteAddr.html

**Comment by marcellmittnacht** [comment]
Okay, actually I found this struct, though I struggled how to access it. Thank you for the help @djarb !

If someone who is new to poem & rust like me, here is how I could access to it, simply by adding it to the parameter list.

#[oai(path = "/test", method = "post")]
async fn test(&self, some_post_data: Json<SomeData>, remote_addr: RemoteAddr) -> Result<SomeResponseResult, SomeResponseError> {
  let user_ip_addr = .....
}

**Comment by marcellmittnacht** [comment]
Okay, actually I found this struct, though I struggled how to access it. Thank you for the help @djarb !

If someone who is new to poem & rust like me, here is how I could access to it, simply by adding it to the parameter list.

#[oai(path = "/test", method = "post")]
async fn test(&self, some_post_data: Json, remote_addr: RemoteAddr) -> Result<SomeResponseResult, SomeResponseError> {
let user_ip_addr = .....
}
