### ISSUE TITLE
hyper 1.0 has been released

### ISSUE THREAD

**Issue by root-talis** [poem-web/poem#696]
## Description of the feature
hyper v1.0 [has been released](https://github.com/hyperium/hyper/releases). Currently Poem is using hyper v0.14. Time to upgrade?

**Comment by sunli829** [comment]
I'm working on it, and the changes are huge so progress will be slow.

**Comment by xamgore** [comment]
@sunli829, take your time. The project is incredible, same as you, so many 谢谢! If you need any help with the community and issues triage, let us know 😌

**Comment by attila-lin** [comment]
sunli finished!

Please use the new version!
