### ISSUE TITLE
Websocket Handler Fails: Multiple Path Parameters

### ISSUE THREAD

**Issue by nicoburniske** [poem-web/poem#702]
## Expected Behavior
Defining a websocket handler with multiple path parameters should be callable

for this server

```rust

#[handler]
fn ws(Path(first): Path<String>, Path(second): Path<String>, ws: WebSocket) -> impl IntoResponse {
   todo!()
}

// some main function

let address = "0.0.0.0:3123";

let app = Route::new().at("/ws/:first/:second", get(ws));

Server::new(TcpListener::bind(address)).run(app).await

```

this client request should succeed.

```rust
let url = format!("ws://{address}/ws/first/second");
let url = Url::parse(&url).expect("Valid URL");
let maybe_error = tokio_tungstenite::connect_async(url).await

```

## Actual Behavior

Making a client request fails with Http Error Status 400 + body `invalid path params`

Using one path parameter works however.

## Steps to Reproduce the Problem

Full Reproduction -> https://github.com/nicoburniske/poem_repro

**Comment by Joeyscat** [comment]
This is an example of using multiple path parameters, Path((name, age)): Path<(String, u32)>, where name and age need to be placed in a tuple instead of two parameters

```rust
#[handler]
fn hello(Path((name, age)): Path<(String, u32)>) -> String {
    format!("hello: {name}, {age}", name = name, age = age)
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "poem=debug");
    }
    tracing_subscriber::fmt::init();

    let app = Route::new()
        .at("/hello/:name/:age", get(hello))
        .with(Tracing);
    Server::new(TcpListener::bind("0.0.0.0:3000"))
        .name("hello-world")
        .run(app)
        .await
}
```

**Comment by nicoburniske** [comment]
This works, but I'm unclear about why some endpoints can use multiple path parameters, but this one cannot.
