### ISSUE TITLE
Does poem support http2?

### ISSUE THREAD

**Issue by Hao2203** [poem-web/poem#724]
Does poem support http2?

**Comment by DDtKey** [comment]
It definitely does, poem utilizes `hyper`.

And would expect to support HTTP/3 in the future (#506), once hyper stabilize the feature.

**Comment by Hao2203** [comment]
> It definitely does, poem utilizes `hyper`.
> 
> And would expect to support HTTP/3 in the future (#506), once hyper stabilize the feature.

That's cool!
