### ISSUE TITLE
ServerSide Cache feature

### ISSUE THREAD

**Issue by lazywalker** [poem-web/poem#75]
## Description of the feature
ServerSide Cache is a common scenario in web application especially with heavy loaded, it will be good to have a Cache extractor which can use DiskCache or RedisCache as CacheStore. it's quite similar to ServerSession. 

Thanks :)

**Comment by sunli829** [comment]
I need to consider whether `Poem` should provide this feature.

**Comment by lazywalker** [comment]
> I need to consider whether `Poem` should provide this feature.

Sure:)
Take your time it was just a suggestion, cache in the old school style
