### ISSUE TITLE
Expose the underlying file under Multipart:Upload or have a function which returns the uploaded file size.

### ISSUE THREAD

**Issue by mmittnacht** [poem-web/poem#765]
## Description of the feature

I would like to ask if it's possible for a helper function under the Multipart:Upload structure, which returns the uploaded file's size by Metadata::MetadataExt::size function?

**Comment by sunli829** [comment]
added `Upload::size` method

**Comment by mmittnacht** [comment]
I appreciate it, thank you very much!
