### ISSUE TITLE
[SecurityScheme] "checker" function always returns the same error

### ISSUE THREAD

**Issue by rxdiscovery** [poem-web/poem#777]
Hello,

I've noticed that the "checker" function always returns the same error in SecurityScheme, even if you define a different one.

```rust
#[oai(
    rename = "JwtSecurityScheme",
    ty = "bearer",
    bearer_format = "JWT",
    key_in = "header",
    key_name = "Bearer",
    checker = "checker_api_jwt_auth",
)]
pub struct JwtSecurityScheme(pub String);

#[derive(Debug, thiserror::Error)]
#[error("FORBIDDEN ! CUSTOM !!!!!")]
pub struct ForbiddenError;

impl ResponseError for ForbiddenError {
    fn status(&self) -> StatusCode {
        StatusCode::FORBIDDEN
    }
}

async fn checker_api_jwt_auth(_req: &Request, bearer: Bearer) -> poem::Result<String> {
    println!("bearer : {:?}", bearer.token);
    Err(ForbiddenError)?
}
```

it always returns : 

```
401 | Error: Unauthorized
Response body (Unrecognized response type; displaying content as text. <--- no schema description) : 
authorization error  <---- body
```

whereas normally it should return ( Forbidden(403) not Unauthorized(401)):  

```
403 | Error: Forbidden
Response body (PlainText  <---Good schema description) : 
FORBIDDEN ! CUSTOM !!!!!  <---- body
```

so there's no difference between a checker that returns an Option or a Result.

thank you in advance :+1:

**Comment by sunli829** [comment]
It is not a bug, If the `Authorization` header is not included in the request, a `401` error will be responded, and `checker_api_jwt_auth` has not been called at this time.

**Comment by rxdiscovery** [comment]
Thank you very much for this information, Poem is very rich in features, it would be nice if the documentation described in detail all its possibilities.
