### ISSUE TITLE
poem-openapi 5.0.1 is incompatible with poem-openapi-derive 5.0.0

### ISSUE THREAD

**Issue by antoninfin** [poem-web/poem#820]
`poem-openapi` 5.0.1 was released while `peom-openapi-derive` wasn't. However `poem-api` 5.0.1 `__private` module no longer reexports `static_assertions` which `poem-openapi-derive` 5.0.0 will try to use leading to compilation errors on unions a with discriminator name:

```
101 | #[derive(poem_openapi::Union, Debug, Clone)]
    |          ^^^^^^^^^^^^^^^^^^^ could not find `static_assertions` in `__private`
```

Could you please release `poem-openapi-derive` 5.0.1 with latest changes?

**Comment by sunli829** [comment]
fixed in `v5.0.2` 🙂
