### ISSUE TITLE
The api doc request response 502 when set the host `0.0.0.0`

### ISSUE THREAD

**Issue by zhuyu4839** [poem-web/poem#832]
## Expected Behavior
The api doc output should be:
```html
<div class="servers">
 <label for="servers">
  <select>
   <option value="http://127.0.0.1:xxx/xxx">http://127.0.0.1:xxx/xxx</option>
  </select>
 </label>
</div>
```
or
```html
<div class="servers">
 <label for="servers">
  <select>
   <option value="http://pc-ip:xxx/xxx">http://pc-ip:xxx/xxx</option>
  </select>
 </label>
</div>
```

## Actual Behavior
```html
<div class="servers">
 <label for="servers">
  <select>
   <option value="http://0.0.0.0:xxx/xxx">http://0.0.0.0:xxx/xxx</option>
  </select>
 </label>
</div>
```

## Steps to Reproduce the Problem

1. OpenApiService::new(...)..server("http://0.0.0.0:8080")

## Specifications

- Version: poem-openai 5.0.2
- Platform:
- Subsystem:

**Comment by zhuyu4839** [comment]
Temp code:
![image](https://github.com/poem-web/poem/assets/15953541/aebb0016-34b0-47e8-80d1-3cecd88ac6ff)

**Comment by sunli829** [comment]
Not a bug, the server method is only used to specify an accessible server address. You should use `api.server("http://127.0.0.1:8080")`.
