### ISSUE TITLE
Cannot use `ParseError` as an `Error` or even `Display` type

### ISSUE THREAD

**Issue by Shadow53** [poem-web/poem#889]
## Expected Behavior

I expect to be able to use [`ParseError`](https://github.com/poem-web/poem/blob/f81424dedeec44cbdf4dbe2e828b0d3bbf579486/poem-openapi/src/types/error.rs#L12) as a root error for another error type, e.g.

```rust
#[derive(thiserror::Error)]
pub enum FooError<T> where T: ParseFromJSON {
    // ... Others...
    #[error(transparent)]
    // Or #[error("failed to parse: {0}")]
    Parse(#[from] ParseError<T>),
}
```

I'd expect the following to be implemented on the error type:

1. `Display`
2. `std::error::Error`
3. A method `fn message(&self) -> &str` to access the message without wrapping the inner `String` 

## Actual Behavior

This is not possible because `ParseError` does not implement `Display` and does not provide a way to take a reference to the inner error string. 

## Steps to Reproduce the Problem

1. Copy the above example to a Rust file and add the necessary imports
2. Try to compile the file
3. See that it fails

## Specifications

- Version: `poem-openapi v5.1.1` `poem v3.1.0`
- Platform: MacOS
- Subsystem: N/A

**Comment by sunli829** [comment]
added `ParseError::message` method in `poem-openapi v5.1.2`
