### ISSUE TITLE
Reason why WebSocket connection works on Chromium but not Firefox?

### ISSUE THREAD

**Issue by FnordlikeCrane** [poem-web/poem#91]
I would normally submit this as a bug but I'm not sure if this is an issue with Poem or Firefox.
I have been using the WebSocket Chat example provided in this repository as a reference for a project I'm working on, however I've noticed that there is always an issue connecting to the the WebSocket with Firefox but not Chromium.

## Expected Behavior

WebSocket code from the example provided in this repository should function regardless of web browser.

## Actual Behavior

WebSocket fails to establish connection on Firefox but functions properly on Chromium.
Error from the Firefox console: `Firefox can’t establish a connection to the server at ws://127.0.0.1:3000/ws.`

## Specifications

- Poem Version: `1.0.26`
- Firefox Version: `94.0`
- Chromium Version: `95.0.4638.69 snap`
- Platform: Ubuntu `21.04`

**Comment by sunli829** [comment]
Thank you for reporting this bug, it has been fixed in `1.0.27`.
