### ISSUE TITLE
priority of multiple middleware.

### ISSUE THREAD

**Issue by bingryan** [poem-web/poem#97]
if there are multiple middleware, How to deal with their priority.

**Comment by sunli829** [comment]
In the following example, the `M2` middleware will be executed before `M1`, which is very similar to `std::iterator::Iterator`. Each `with` function will generate a new endpoint that wraps the previous endpoint.

```rust
ep.with(M1).with(M2)
```

**Comment by bingryan** [comment]
> In the following example, the `M2` middleware will be executed before `M1`, which is very similar to `std::iterator::Iterator`. Each `with` function will generate a new endpoint that wraps the previous endpoint.
> 
> ```rust
> ep.with(M1).with(M2)
> ```

that's cool, before you answer. I thought about it for a while, add a priority value, such as:

```
ep.with_multi([(1,M1),(2,M2)])

ep.around_multi([(1,M1),(2,M2)])
```

or add global middleware priority value , such as:

```
Route::new().xxx(
	"api",
	Route::new().with([M2]),
	Route::new().with([M1,M3]),
).middlewares([
	(M1, 1),
	(M2, 2),
	(M3, 10),
])
```

**Comment by sunli829** [comment]
You can use multiple middleware with the `with` method:

```rust
ep.with((M1, M2))
```

But you cannot use integers to specify their priority value.
The principle of middleware is to wrap previous endpoint to generate a new one, so this is impossible to achieve.
