### ISSUE TITLE
CSRF Middleware

### ISSUE THREAD

**Issue by shujaatak** [poem-web/poem#98]
Can you please add Double-Submit Token CSRF middleware to poem like there is such middlware for Actix-Web https://github.com/edward-shen/actix-csrf

**Comment by sunli829** [comment]
Okay, I will add this.

**Comment by shujaatak** [comment]
Some pointers here and there https://github.com/iwismer/actix-auth-example

**Comment by sunli829** [comment]
I added CSRF middleware to the `master` branch. 

Here is an example:

https://github.com/poem-web/poem/tree/master/examples/poem/csrf

**Comment by shujaatak** [comment]
> I added CSRF middleware to the `master` branch.
> 
> Here is an example:
> 
> https://github.com/poem-web/poem/tree/master/examples/poem/csrf

@sunli829 Unbelievably Awesome! Extremely superb and quick support! You are a real champion in what you are doing!
Thank you so much brother for the Poem project and the continuous support! Extremely grateful to you!

**Comment by sunli829** [comment]
Released in `v1.0.32`
