### ISSUE TITLE
Middleware to protect authenticated routes from unauthenticated access.

### ISSUE THREAD

**Issue by shujaatak** [poem-web/poem#99]
If a session is authenticated, then the request should be dispatched to the matching handler and if unauthenticated, it should be redirected to a user specified route, ideally a sign in route.

Related project for Actix-Web: https://github.com/realaravinth/actix-auth-middleware

@sunli829 As I have started using **Poem** since yesterday so currently I'm in **_leeches mode_** but as I grow my understanding of poem I will start contributing to the project.

**Comment by shujaatak** [comment]
I don't know if this functionality is already there is Poem and I know Poem is surprisingly amazing project with amazing hidden functionalities which I think I will document in the near future.

**Comment by sunli829** [comment]
Currently Poem does not provide this, it is very simple to implement it, but I am not sure whether Poem should include this feature. 🙂

**Comment by shujaatak** [comment]
> Currently Poem does not provide this, it is very simple to implement it, but I am not sure whether Poem should include this feature. slightly_smiling_face

It would be so awesome if you please include it. 
Like me, many Poem beginners would highly benefit from it and truly everything would seem like a poem :)

**Comment by nasimashujaat** [comment]
I am also waiting for this feature.

**Comment by sunli829** [comment]
This is very simple to do, and I don't think it is necessary to make a middleware specifically for this. 🙂

**Comment by shujaatak** [comment]
@sunli829 Can you share sample implementation here to show how to do this in poem please?

**Comment by sunli829** [comment]
Hope this example can help you.

https://github.com/poem-web/poem/tree/master/examples/poem/auth

**Comment by shujaatak** [comment]
> Hope this example can help you.
> 
> https://github.com/poem-web/poem/tree/master/examples/poem/auth

@sunli829 Indeed it's really helpful!

 What I love about Poem is that it has such a great list of awesome [examples](https://github.com/poem-web/poem/tree/master/examples)!
